/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pryfiguras2d;

/**
 *
 * @author Usuario
 */
public class WinLinea extends javax.swing.JFrame {
    ClsLinea l1,l2;
    float x,y;
    boolean primer=true;
    ClsPunto pi,pf;
    /**
     * Creates new form WinLinea
     */
    public WinLinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDisplay = new javax.swing.JTextField();
        BtnCoordX = new javax.swing.JButton();
        BtnCoordY = new javax.swing.JButton();
        BtnEcuacion = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnCoordenadas = new javax.swing.JButton();
        BtnAngulo = new javax.swing.JButton();
        BtnLongitud1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtDisplay.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        BtnCoordX.setText("Coordenada X");
        BtnCoordX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoordXActionPerformed(evt);
            }
        });

        BtnCoordY.setText("Coordenada Y");
        BtnCoordY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoordYActionPerformed(evt);
            }
        });

        BtnEcuacion.setText("Ecuacion");
        BtnEcuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEcuacionActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");

        BtnCoordenadas.setText("Coordenadas");
        BtnCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoordenadasActionPerformed(evt);
            }
        });

        BtnAngulo.setText("Angulo");
        BtnAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnguloActionPerformed(evt);
            }
        });

        BtnLongitud1.setText("Longitud");
        BtnLongitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLongitud1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtDisplay)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnEcuacion)
                            .addComponent(BtnCoordX))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCoordY)
                            .addComponent(BtnCoordenadas)
                            .addComponent(BtnAngulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(BtnLimpiar)
                        .addGap(42, 42, 42)
                        .addComponent(BtnSalir)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(BtnLongitud1)
                    .addContainerGap(215, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCoordX)
                    .addComponent(BtnCoordY))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEcuacion)
                    .addComponent(BtnCoordenadas))
                .addGap(26, 26, 26)
                .addComponent(BtnAngulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnSalir))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(203, Short.MAX_VALUE)
                    .addComponent(BtnLongitud1)
                    .addGap(74, 74, 74)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCoordXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoordXActionPerformed
        /**WinPunto wp=new WinPunto ();
        wp.setVisible(true);
        //datos que deben regresar los datos de un formulario al otro 
        pi=new ClsPunto (wp.p.cx(),wp.p.cy());
        TxtDisplay.setText(pi.rect());
        **/
        x=Float.parseFloat(TxtDisplay.getText());
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled (false);
    }//GEN-LAST:event_BtnCoordXActionPerformed

    private void BtnCoordYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoordYActionPerformed
        /**WinPunto wp=new WinPunto ();
        wp.setVisible(true);
        //datos que deben regresar los datos de un formulario al otro 
        pf=new ClsPunto (wp.q.cx(),wp.q.cy());
        TxtDisplay.setText(pf.rect());
        **/
        y=Float.parseFloat(TxtDisplay.getText());
        if (primer)
        {
           pi= new ClsPunto(x,y);
           TxtDisplay.setText("Punto Inicial: "+ pi.toString());
           primer=false;
        }
        else
        {
           pf= new ClsPunto(x,y);
           primer=true;
           l1=new ClsLinea(pi,pf);
           TxtDisplay.setText(l1.verlinea());
           primer=false;
        }
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled(true);
        
    }//GEN-LAST:event_BtnCoordYActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        primer=true;
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnEcuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEcuacionActionPerformed
        TxtDisplay.setText(l1.ecuacion());
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnEcuacionActionPerformed

    private void BtnAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnguloActionPerformed
        TxtDisplay.setText(String.valueOf(l1.angulo()));
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnAnguloActionPerformed

    private void BtnLongitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLongitud1ActionPerformed
        TxtDisplay.setText(String.valueOf(l1.longitud()));
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnLongitud1ActionPerformed

    private void BtnCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoordenadasActionPerformed
        TxtDisplay.setText(l1.toString());
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnCoordenadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAngulo;
    private javax.swing.JButton BtnCoordX;
    private javax.swing.JButton BtnCoordY;
    private javax.swing.JButton BtnCoordenadas;
    private javax.swing.JButton BtnEcuacion;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnLongitud1;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTextField TxtDisplay;
    // End of variables declaration//GEN-END:variables
}
