/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaNegocio.*;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class WinCaluladora extends javax.swing.JFrame {
    Operaciones p,q;
    int tipo,codigo;
    float i,r;
    int m,n;
    /**
     * Creates new form WinCaluladora
     */
    public WinCaluladora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(64,178,240));
        this.PnlFraccion.setBackground(new Color(64,178,240));
        this.PnlComplejo.setBackground(new Color(64,178,240));
        this.PnlPunto.setBackground(new Color(64,178,240));
        this.PnlFraccion.setVisible(false);
        this.PnlComplejo.setVisible(false);
        this.PnlPunto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TxtPantalla = new javax.swing.JTextField();
        OptFraccion = new javax.swing.JRadioButton();
        OptComplejo = new javax.swing.JRadioButton();
        OptPunto = new javax.swing.JRadioButton();
        BtnOperando1 = new javax.swing.JButton();
        BtnOperando2 = new javax.swing.JButton();
        BtnMas = new javax.swing.JButton();
        BtnMenos = new javax.swing.JButton();
        BtnPor = new javax.swing.JButton();
        BtnPara = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        PnlFraccion = new javax.swing.JPanel();
        BtnSimplificar = new javax.swing.JButton();
        BtnValor = new javax.swing.JButton();
        PnlPunto = new javax.swing.JPanel();
        BtnPolar = new javax.swing.JButton();
        PnlComplejo = new javax.swing.JPanel();
        BtnConjugada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Calculadora Multiple Usando Interface");

        TxtPantalla.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        buttonGroup1.add(OptFraccion);
        OptFraccion.setText("Fracción");
        OptFraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptFraccionActionPerformed(evt);
            }
        });

        buttonGroup1.add(OptComplejo);
        OptComplejo.setText("Complejo");
        OptComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptComplejoActionPerformed(evt);
            }
        });

        buttonGroup1.add(OptPunto);
        OptPunto.setText("Punto");
        OptPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptPuntoActionPerformed(evt);
            }
        });

        BtnOperando1.setText("Operando 1");
        BtnOperando1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOperando1ActionPerformed(evt);
            }
        });

        BtnOperando2.setText("Operando 2");
        BtnOperando2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOperando2ActionPerformed(evt);
            }
        });

        BtnMas.setText("+");
        BtnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMasActionPerformed(evt);
            }
        });

        BtnMenos.setText("-");
        BtnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenosActionPerformed(evt);
            }
        });

        BtnPor.setText("*");
        BtnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPorActionPerformed(evt);
            }
        });

        BtnPara.setText("/");
        BtnPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnParaActionPerformed(evt);
            }
        });

        BtnIgual.setText("=");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnSimplificar.setText("Simplificar");
        BtnSimplificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimplificarActionPerformed(evt);
            }
        });

        BtnValor.setText("Valor Decimal");
        BtnValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFraccionLayout = new javax.swing.GroupLayout(PnlFraccion);
        PnlFraccion.setLayout(PnlFraccionLayout);
        PnlFraccionLayout.setHorizontalGroup(
            PnlFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFraccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFraccionLayout.createSequentialGroup()
                        .addComponent(BtnSimplificar)
                        .addContainerGap())))
        );
        PnlFraccionLayout.setVerticalGroup(
            PnlFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFraccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSimplificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnPolar.setText("Coordenadas polares");
        BtnPolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPolarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlPuntoLayout = new javax.swing.GroupLayout(PnlPunto);
        PnlPunto.setLayout(PnlPuntoLayout);
        PnlPuntoLayout.setHorizontalGroup(
            PnlPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPuntoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnPolar))
        );
        PnlPuntoLayout.setVerticalGroup(
            PnlPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnPolar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnConjugada.setText("Conjugada");
        BtnConjugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConjugadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlComplejoLayout = new javax.swing.GroupLayout(PnlComplejo);
        PnlComplejo.setLayout(PnlComplejoLayout);
        PnlComplejoLayout.setHorizontalGroup(
            PnlComplejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlComplejoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnConjugada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlComplejoLayout.setVerticalGroup(
            PnlComplejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlComplejoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnConjugada)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnPor)
                                    .addComponent(BtnMas))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnMenos)
                                    .addComponent(BtnPara)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(BtnIgual))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(BtnOperando1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnOperando2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(TxtPantalla, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLimpiar)
                .addGap(73, 73, 73)
                .addComponent(BtnSalir)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PnlFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(PnlPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(PnlComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(OptFraccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OptComplejo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OptPunto)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TxtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptFraccion)
                    .addComponent(OptComplejo)
                    .addComponent(OptPunto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOperando1)
                    .addComponent(BtnOperando2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMas)
                    .addComponent(BtnMenos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnPara)
                    .addComponent(BtnPor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnIgual)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PnlFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PnlComplejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PnlPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalir)
                    .addComponent(BtnLimpiar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OptFraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptFraccionActionPerformed
        BtnOperando1.setText("Numerador");
        BtnOperando2.setText("Denominador");
        TxtPantalla.requestFocus();
        PnlComplejo.setVisible(false);
        PnlFraccion.setVisible(true);
        PnlPunto.setVisible(false);
        tipo=1;
    }//GEN-LAST:event_OptFraccionActionPerformed

    private void OptComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptComplejoActionPerformed
        BtnOperando1.setText("Real");
        BtnOperando2.setText("Imaginario");
        PnlComplejo.setVisible(true);
        PnlFraccion.setVisible(false);
        PnlPunto.setVisible(false);
        TxtPantalla.requestFocus();
        tipo=2;
    }//GEN-LAST:event_OptComplejoActionPerformed

    private void OptPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptPuntoActionPerformed
        BtnOperando1.setText("Coordenada X");
        BtnOperando2.setText("Coordenada Y");
        TxtPantalla.requestFocus();
        PnlComplejo.setVisible(false);
        PnlFraccion.setVisible(false);
        PnlPunto.setVisible(true);
        tipo=3;
    }//GEN-LAST:event_OptPuntoActionPerformed

    private void BtnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasActionPerformed
        p=q;
        TxtPantalla.setText(null);
        TxtPantalla.requestFocus();
        codigo=1;
    }//GEN-LAST:event_BtnMasActionPerformed

    private void BtnOperando1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOperando1ActionPerformed
        r=Float.parseFloat(TxtPantalla.getText());
        TxtPantalla.setText(null);
        TxtPantalla.requestFocus();
    }//GEN-LAST:event_BtnOperando1ActionPerformed

    private void BtnOperando2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOperando2ActionPerformed
        i=Float.parseFloat(TxtPantalla.getText());
        switch(tipo){
            case 1:
            {
                m=(int)i;
                n=(int)r;
                q=new ClsFraccion(n,m);
                break;
            }
            case 2:
            {
                q=new ClsComplejos(r,i);
                break;
            }
            case 3:{
                q=new ClsPunto(r,i);
                break;
            }   
        }
        TxtPantalla.setText(q.toString());
        TxtPantalla.requestFocus();
    }//GEN-LAST:event_BtnOperando2ActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        TxtPantalla.setText(null);
        BtnOperando1.setText("Operando 1");
        BtnOperando2.setText("Operando 2");
        buttonGroup1.clearSelection();
        this.PnlFraccion.setVisible(false);
        this.PnlComplejo.setVisible(false);
        this.PnlPunto.setVisible(false);
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenosActionPerformed
        p=q;
        TxtPantalla.setText(null);
        TxtPantalla.requestFocus();
        codigo=2;
    }//GEN-LAST:event_BtnMenosActionPerformed

    private void BtnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPorActionPerformed
        p=q;
        TxtPantalla.setText(null);
        TxtPantalla.requestFocus();
        codigo=3;
    }//GEN-LAST:event_BtnPorActionPerformed

    private void BtnParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnParaActionPerformed
        p=q;
        TxtPantalla.setText(null);
        TxtPantalla.requestFocus();
        codigo=4;
    }//GEN-LAST:event_BtnParaActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        switch(codigo){
            case 1:
            {
                q=(Operaciones)p.mas(q);
                break;
            }
            case 2:
            {
                q=(Operaciones)p.menos(q);
                break;
            }
            case 3:
            {
                q=(Operaciones)p.por(q);
                break;
            }
            case 4:
            {
                q=(Operaciones)p.para(q);
                break;
            }
        }
        TxtPantalla.setText(q.toString());
        TxtPantalla.requestFocus();
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnSimplificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimplificarActionPerformed
        ClsFraccion b=new ClsFraccion(n,m);
        b=(ClsFraccion)q;
        b.simplificar();
        TxtPantalla.setText(b.Resultado());
        TxtPantalla.requestFocus();
    }//GEN-LAST:event_BtnSimplificarActionPerformed

    private void BtnValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValorActionPerformed
        ClsFraccion b=new ClsFraccion(n,m);
        b=(ClsFraccion)q;
        TxtPantalla.setText(String.valueOf(b.valor()));
        TxtPantalla.requestFocus();
    }//GEN-LAST:event_BtnValorActionPerformed

    private void BtnConjugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConjugadaActionPerformed
        ClsComplejos b=new ClsComplejos(i,r);
        b=(ClsComplejos)q;
        TxtPantalla.setText(b.Conjugada());
        TxtPantalla.requestFocus();
    }//GEN-LAST:event_BtnConjugadaActionPerformed

    private void BtnPolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPolarActionPerformed
        ClsPunto b=new ClsPunto(i,r);
        b=(ClsPunto)q;
        TxtPantalla.setText(b.polar());
        TxtPantalla.requestFocus();
    }//GEN-LAST:event_BtnPolarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConjugada;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnMas;
    private javax.swing.JButton BtnMenos;
    private javax.swing.JButton BtnOperando1;
    private javax.swing.JButton BtnOperando2;
    private javax.swing.JButton BtnPara;
    private javax.swing.JButton BtnPolar;
    private javax.swing.JButton BtnPor;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSimplificar;
    private javax.swing.JButton BtnValor;
    private javax.swing.JRadioButton OptComplejo;
    private javax.swing.JRadioButton OptFraccion;
    private javax.swing.JRadioButton OptPunto;
    private javax.swing.JPanel PnlComplejo;
    private javax.swing.JPanel PnlFraccion;
    private javax.swing.JPanel PnlPunto;
    private javax.swing.JTextField TxtPantalla;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
