/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class WinMenu extends javax.swing.JFrame {

    /**
     * Creates new form WinMenu
     */
    public WinMenu() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(123,123,123));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opt4 = new javax.swing.JMenu();
        Opt1 = new javax.swing.JMenuItem();
        Opt2 = new javax.swing.JMenuItem();
        Opt3 = new javax.swing.JMenuItem();
        Opt7 = new javax.swing.JMenuItem();
        Opt5 = new javax.swing.JMenuItem();
        MnuEdicion = new javax.swing.JMenu();
        Opt6 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Opt4.setText("Figuras");

        Opt1.setText("Triángulo");
        Opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt1ActionPerformed(evt);
            }
        });
        Opt4.add(Opt1);

        Opt2.setText("Círculo");
        Opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt2ActionPerformed(evt);
            }
        });
        Opt4.add(Opt2);

        Opt3.setText("Cuadrilátero");
        Opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt3ActionPerformed(evt);
            }
        });
        Opt4.add(Opt3);

        Opt7.setText("Polígono");
        Opt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt7ActionPerformed(evt);
            }
        });
        Opt4.add(Opt7);

        Opt5.setText("Salir");
        Opt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt5ActionPerformed(evt);
            }
        });
        Opt4.add(Opt5);

        jMenuBar1.add(Opt4);

        MnuEdicion.setText("Ayuda");

        Opt6.setText("Acerca de");
        Opt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt6ActionPerformed(evt);
            }
        });
        MnuEdicion.add(Opt6);

        jMenuBar1.add(MnuEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt1ActionPerformed
        this.setVisible(false);
        WinTriangulo d= new WinTriangulo();
        d.setVisible(true);
    }//GEN-LAST:event_Opt1ActionPerformed

    private void Opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt2ActionPerformed
       this.setVisible(false);
        WinCirculo d= new WinCirculo();
        d.setVisible(true);
    }//GEN-LAST:event_Opt2ActionPerformed

    private void Opt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt6ActionPerformed
        this.setVisible(false);
        WinAcerca d= new WinAcerca();
        d.setVisible(true);
    }//GEN-LAST:event_Opt6ActionPerformed

    private void Opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt3ActionPerformed
        this.setVisible(false);
        WinCuadrilatero d= new WinCuadrilatero();
        d.setVisible(true);
    }//GEN-LAST:event_Opt3ActionPerformed

    private void Opt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt7ActionPerformed
        this.setVisible(false);
        WinPoligono d= new WinPoligono();
        d.setVisible(true);
    }//GEN-LAST:event_Opt7ActionPerformed

    private void Opt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Opt5ActionPerformed

    /**
     * @param args the command line arguments
     */

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuEdicion;
    private javax.swing.JMenuItem Opt1;
    private javax.swing.JMenuItem Opt2;
    private javax.swing.JMenuItem Opt3;
    private javax.swing.JMenu Opt4;
    private javax.swing.JMenuItem Opt5;
    private javax.swing.JMenuItem Opt6;
    private javax.swing.JMenuItem Opt7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
