/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pryfiguras2d;
    
/**
 *
 * @author Usuario
 */
public class WinLinea extends javax.swing.JFrame {
    ClsLinea l1, l2;
    ClsPunto pi,pf,lect;
    float x,y, valor, valor1;
    boolean primer=true;
    int codigo;
    /**
     * Creates new form WinLinea
     */
    public WinLinea() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtDisplay = new javax.swing.JTextField();
        BtnEcuacion = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnCoordX = new javax.swing.JButton();
        BtnCoordY = new javax.swing.JButton();
        BtnCoordenadas = new javax.swing.JButton();
        BtnAngulo = new javax.swing.JButton();
        BtnLongitud = new javax.swing.JButton();
        BtnSuma = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnResta = new javax.swing.JButton();
        BtnMulti = new javax.swing.JButton();
        BtnDivision = new javax.swing.JButton();
        BtnPolares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplciación Linea ");

        jLabel1.setText("Autor: Freddy Valverde");

        TxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        BtnEcuacion.setText("Ver Ecuación");
        BtnEcuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEcuacionActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnCoordX.setText("Coordenada X");
        BtnCoordX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoordXActionPerformed(evt);
            }
        });

        BtnCoordY.setText("Coordenada Y");
        BtnCoordY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoordYActionPerformed(evt);
            }
        });

        BtnCoordenadas.setText("Coordenadas Rect");
        BtnCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoordenadasActionPerformed(evt);
            }
        });

        BtnAngulo.setText("Angulo");
        BtnAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnguloActionPerformed(evt);
            }
        });

        BtnLongitud.setText("Longitud");
        BtnLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLongitudActionPerformed(evt);
            }
        });

        BtnSuma.setText("Suma");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        BtnIgual.setText("Igual");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnResta.setText("Resta");
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });

        BtnMulti.setText("Multiplicación");
        BtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiActionPerformed(evt);
            }
        });

        BtnDivision.setText("División");
        BtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivisionActionPerformed(evt);
            }
        });

        BtnPolares.setText("Coordenadas polares");
        BtnPolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPolaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCoordY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BtnCoordX)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnSuma)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnResta)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnMulti)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BtnDivision)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(BtnPolares, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCoordX)
                    .addComponent(BtnEcuacion)
                    .addComponent(BtnSuma)
                    .addComponent(BtnResta)
                    .addComponent(BtnMulti)
                    .addComponent(BtnDivision))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnCoordY)
                        .addComponent(BtnCoordenadas))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnAngulo)
                        .addComponent(BtnLongitud)
                        .addComponent(BtnLimpiar)
                        .addComponent(BtnSalir)))
                .addGap(8, 8, 8)
                .addComponent(BtnPolares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIgual)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEcuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEcuacionActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(l1.VerEcuacion());
    }//GEN-LAST:event_BtnEcuacionActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled(true);
        BtnCoordY.setEnabled(true);
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnCoordXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoordXActionPerformed
        // TODO add your handling code here:
        x=Float.parseFloat(TxtDisplay.getText());
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled(false);
    }//GEN-LAST:event_BtnCoordXActionPerformed

    private void BtnCoordYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoordYActionPerformed
        // TODO add your handling code here:
        y=Float.parseFloat(TxtDisplay.getText());
        if (primer){
            pi= new ClsPunto(x,y);
            TxtDisplay.setText("Punto Inicial: " + pi.rectangular());
            primer=false;
        }else{
            pf= new ClsPunto(x,y);
            primer=true;
            l1= new ClsLinea(pi,pf);
            TxtDisplay.setText(l1.VerLinea());
        }
        
        BtnCoordY.setEnabled(false);
    }//GEN-LAST:event_BtnCoordYActionPerformed

    private void BtnCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoordenadasActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(l1.Coordenadas(pi, pf));
    }//GEN-LAST:event_BtnCoordenadasActionPerformed

    private void BtnAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnguloActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText("Angulo de la inclinación de la linea: " + l1.angulo());
    }//GEN-LAST:event_BtnAnguloActionPerformed

    private void BtnLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLongitudActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText("Longitud de la Linea: "+ l1.Longitud());
    }//GEN-LAST:event_BtnLongitudActionPerformed

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        // TODO add your handling code here:
        codigo=1;
        l2= new ClsLinea(l1);
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled(true);
        BtnCoordY.setEnabled(true);
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        // TODO add your handling code here:
        switch(codigo){
            case 1:{
                l1=l2.Suma(l1);
                break;
            }
            case 2:{
                l1=l2.Resta(l1);
                break;
            }
            case 3:{
                valor=Float.parseFloat(TxtDisplay.getText());
                l1=l2.Multiplicacion(valor);
                break;
            }
            case 4:{
                valor1=Float.parseFloat(TxtDisplay.getText());
                l1=l2.Division(valor);
                break;
            }
        }
        TxtDisplay.setText(l1.VerEcuacion());
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        // TODO add your handling code here:
        codigo=2;
        l2= new ClsLinea(l1);
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled(true);
        BtnCoordY.setEnabled(true);
    }//GEN-LAST:event_BtnRestaActionPerformed

    private void BtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiActionPerformed
        // TODO add your handling code here:
        codigo=3;
        l2= new ClsLinea(l1);
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled(true);
        BtnCoordY.setEnabled(true);        
    }//GEN-LAST:event_BtnMultiActionPerformed

    private void BtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivisionActionPerformed
        // TODO add your handling code here:
        codigo=4;
        l2= new ClsLinea(l1);
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnCoordX.setEnabled(true);
        BtnCoordY.setEnabled(true);           
    }//GEN-LAST:event_BtnDivisionActionPerformed

    private void BtnPolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPolaresActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(l1.Polares());
    }//GEN-LAST:event_BtnPolaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAngulo;
    private javax.swing.JButton BtnCoordX;
    private javax.swing.JButton BtnCoordY;
    private javax.swing.JButton BtnCoordenadas;
    private javax.swing.JButton BtnDivision;
    private javax.swing.JButton BtnEcuacion;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnLongitud;
    private javax.swing.JButton BtnMulti;
    private javax.swing.JButton BtnPolares;
    private javax.swing.JButton BtnResta;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JTextField TxtDisplay;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
