/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;
import CapaDatos.Conexion;
import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import CapaDatos.*;
import CapaNegocio.*;
/**
 *
 * @author user
 */
public class WinPrincipal extends javax.swing.JFrame {
    Conexion directa;
    Cliente id,cedula,nombre,apellido,fecha,direccion,telefono,celular,email;
    Vendedor idv,cedulav,nombrev,apellidov,direcionv,telefonov,celularv;
    Producto idp,nombreproducto,precio,cantidad;
    Factura nofactura,fechaf,clavec,clavev;
    DetalleFactura clavefactura,claveproducto,cant;
    /**
     * Creates new form WinPrincipal
     */
    public WinPrincipal() {
        initComponents();
        ArchBase.setVisible(false);
        PnlCliente.setVisible(false);
        PnlListaClientes.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlListaVendedor.setVisible(false);
        PnlFacturas.setVisible(false);
        PnlListafacturas.setVisible(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color (231,217,189));
        this.PnlCliente.setBackground(new Color (231,217,189));
        this.PnlListaClientes.setBackground(new Color (231,217,189));
        this.PnlVendedor.setBackground(new Color (231,217,189));
        this.PnlListaVendedor.setBackground(new Color (231,217,189));
        this.PnlFacturas.setBackground(new Color (231,217,189));
        this.PnlListafacturas.setBackground(new Color (231,217,189));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        TxtCelCliente = new javax.swing.JTextField();
        TxtTelefCliente = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtNacimiento = new javax.swing.JTextField();
        TxtApelCliente = new javax.swing.JTextField();
        TxtNomCliente = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        BtnActuaCliente = new javax.swing.JButton();
        BtnModificarCliente = new javax.swing.JButton();
        BtnBuscarCliente = new javax.swing.JButton();
        BtnIngresarCliente = new javax.swing.JButton();
        BtnEliminarClinete = new javax.swing.JButton();
        PnlListafacturas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        TxtNdeFactura = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblFacturas = new javax.swing.JTable();
        BtnBuscarFact = new javax.swing.JButton();
        PnlFacturas = new javax.swing.JPanel();
        PnlListaVendedor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TxtIdentificacionVendedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblVendedor = new javax.swing.JTable();
        BtnBuscarVende = new javax.swing.JButton();
        PnlVendedor = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TxtCelCliente1 = new javax.swing.JTextField();
        TxtTelefCliente1 = new javax.swing.JTextField();
        TxtDireccion1 = new javax.swing.JTextField();
        TxtApelCliente1 = new javax.swing.JTextField();
        TxtNomCliente1 = new javax.swing.JTextField();
        TxtCedula1 = new javax.swing.JTextField();
        BtnActuaCliente1 = new javax.swing.JButton();
        BtnModificarCliente1 = new javax.swing.JButton();
        BtnBuscarCliente1 = new javax.swing.JButton();
        BtnIngresarCliente1 = new javax.swing.JButton();
        BtnEliminarClinete1 = new javax.swing.JButton();
        PnlListaClientes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TxtIdentificacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCliente = new javax.swing.JTable();
        BtnBuscar = new javax.swing.JButton();
        ArchBase = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuDatos = new javax.swing.JMenu();
        ItmAbrir = new javax.swing.JMenuItem();
        ItmSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItmRecorrer = new javax.swing.JMenuItem();
        ItmNuevo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ItmLitsaVendedor = new javax.swing.JMenuItem();
        ItmNuevoVendedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ItmNuevaFactura = new javax.swing.JMenuItem();
        ItmLstFacturas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ItmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion de Facturación");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Nombre:");
        PnlCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Apellido:");
        PnlCliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Dirección:");
        PnlCliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Celular:");
        PnlCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");
        PnlCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel6.setText("Cedula:");
        PnlCliente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel7.setText("Email:");
        PnlCliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel8.setText("Teléfono:");
        PnlCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        TxtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 480, -1));

        TxtCelCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtCelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, -1));

        TxtTelefCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtTelefCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 200, -1));

        TxtDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 480, -1));

        TxtNacimiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, -1));

        TxtApelCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtApelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, -1));

        TxtNomCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, -1));

        TxtCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlCliente.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));

        BtnActuaCliente.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnActuaCliente.setText("Actualizar Registros");
        PnlCliente.add(BtnActuaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        BtnModificarCliente.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnModificarCliente.setText("Modificar Cliente");
        PnlCliente.add(BtnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        BtnBuscarCliente.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnBuscarCliente.setText("Busqueda de Cliente");
        BtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarClienteActionPerformed(evt);
            }
        });
        PnlCliente.add(BtnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        BtnIngresarCliente.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnIngresarCliente.setText("Insertar Cliente");
        BtnIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarClienteActionPerformed(evt);
            }
        });
        PnlCliente.add(BtnIngresarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        BtnEliminarClinete.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnEliminarClinete.setText("Eliminar Cliente");
        PnlCliente.add(BtnEliminarClinete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        getContentPane().add(PnlCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 660, 500));

        PnlListafacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel15.setText("Nº de Factura:");
        PnlListafacturas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        TxtNdeFactura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtNdeFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNdeFacturaActionPerformed(evt);
            }
        });
        PnlListafacturas.add(TxtNdeFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 200, -1));

        TblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TblFacturas);

        PnlListafacturas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 620, 360));

        BtnBuscarFact.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnBuscarFact.setText("Buscar");
        PnlListafacturas.add(BtnBuscarFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        getContentPane().add(PnlListafacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 500));

        PnlFacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PnlFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 690, 490));

        PnlListaVendedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel10.setText("Identificación: ");
        PnlListaVendedor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        TxtIdentificacionVendedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlListaVendedor.add(TxtIdentificacionVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 200, -1));

        TblVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TblVendedor);

        PnlListaVendedor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 620, 360));

        BtnBuscarVende.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnBuscarVende.setText("Buscar");
        PnlListaVendedor.add(BtnBuscarVende, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        getContentPane().add(PnlListaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 500));

        PnlVendedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel11.setText("Dirección:");
        PnlVendedor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel12.setText("Celular:");
        PnlVendedor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel13.setText("Nombre:");
        PnlVendedor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel14.setText("Apellido:");
        PnlVendedor.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel16.setText("Cedula:");
        PnlVendedor.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel17.setText("Teléfono:");
        PnlVendedor.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        TxtCelCliente1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlVendedor.add(TxtCelCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 200, -1));

        TxtTelefCliente1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlVendedor.add(TxtTelefCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, -1));

        TxtDireccion1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlVendedor.add(TxtDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 480, -1));

        TxtApelCliente1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlVendedor.add(TxtApelCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, -1));

        TxtNomCliente1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlVendedor.add(TxtNomCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, -1));

        TxtCedula1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlVendedor.add(TxtCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));

        BtnActuaCliente1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnActuaCliente1.setText("Actualizar Registros");
        PnlVendedor.add(BtnActuaCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        BtnModificarCliente1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnModificarCliente1.setText("Modificar Vendedor");
        PnlVendedor.add(BtnModificarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        BtnBuscarCliente1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnBuscarCliente1.setText("Busqueda de Vendedor");
        BtnBuscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCliente1ActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnBuscarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        BtnIngresarCliente1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnIngresarCliente1.setText("Insertar Vendedor");
        PnlVendedor.add(BtnIngresarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        BtnEliminarClinete1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnEliminarClinete1.setText("Eliminar Vendedor");
        PnlVendedor.add(BtnEliminarClinete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        getContentPane().add(PnlVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 690, 520));

        PnlListaClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel9.setText("Identificación: ");
        PnlListaClientes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        TxtIdentificacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PnlListaClientes.add(TxtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 200, -1));

        TblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblCliente);

        PnlListaClientes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 620, 360));

        BtnBuscar.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        BtnBuscar.setText("Buscar");
        PnlListaClientes.add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        getContentPane().add(PnlListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 680, 500));

        ArchBase.setCurrentDirectory(new java.io.File("C:\\Users\\Usuario\\Equipo"));
        ArchBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchBaseActionPerformed(evt);
            }
        });
        getContentPane().add(ArchBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 680, 510));

        MnuDatos.setText("Sistema");

        ItmAbrir.setText("Conexion");
        ItmAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmAbrirActionPerformed(evt);
            }
        });
        MnuDatos.add(ItmAbrir);

        ItmSalir.setText("Salir");
        ItmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmSalirActionPerformed(evt);
            }
        });
        MnuDatos.add(ItmSalir);

        jMenuBar1.add(MnuDatos);

        jMenu2.setText("Cliente");

        ItmRecorrer.setText("Lista");
        ItmRecorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmRecorrerActionPerformed(evt);
            }
        });
        jMenu2.add(ItmRecorrer);

        ItmNuevo.setText("Nuevo");
        ItmNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmNuevoActionPerformed(evt);
            }
        });
        jMenu2.add(ItmNuevo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vendedor");

        ItmLitsaVendedor.setText("Lista");
        ItmLitsaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmLitsaVendedorActionPerformed(evt);
            }
        });
        jMenu3.add(ItmLitsaVendedor);

        ItmNuevoVendedor.setText("Nuevo");
        ItmNuevoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmNuevoVendedorActionPerformed(evt);
            }
        });
        jMenu3.add(ItmNuevoVendedor);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Factura");

        ItmNuevaFactura.setText(" Nueva");
        jMenu4.add(ItmNuevaFactura);

        ItmLstFacturas.setText("Lista de Facturas");
        jMenu4.add(ItmLstFacturas);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Ayuda");

        ItmAcerca.setText("Acerca de ");
        jMenu1.add(ItmAcerca);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmAbrirActionPerformed
        ArchBase.setVisible(true);
    }//GEN-LAST:event_ItmAbrirActionPerformed

    private void ItmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ItmSalirActionPerformed

    private void ItmRecorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmRecorrerActionPerformed
        ArchBase.setVisible(false);
        PnlCliente.setVisible(false);
        PnlListaClientes.setVisible(true);
    }//GEN-LAST:event_ItmRecorrerActionPerformed

    private void ItmNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmNuevoActionPerformed
        PnlCliente.setVisible(true);
        ArchBase.setVisible(false);
        PnlListaClientes.setVisible(false);
        
    }//GEN-LAST:event_ItmNuevoActionPerformed

    private void ItmLitsaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmLitsaVendedorActionPerformed
        ArchBase.setVisible(false);
        PnlCliente.setVisible(false);
        PnlListaClientes.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlListaVendedor.setVisible(true);
    }//GEN-LAST:event_ItmLitsaVendedorActionPerformed

    private void ItmNuevoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmNuevoVendedorActionPerformed
        PnlVendedor.setVisible(true);
        ArchBase.setVisible(false);
        PnlCliente.setVisible(false);
        PnlListaClientes.setVisible(false);
    }//GEN-LAST:event_ItmNuevoVendedorActionPerformed

    private void ArchBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchBaseActionPerformed
        File f=ArchBase.getSelectedFile();
        String bd=f.getAbsolutePath();
        ArchBase.setVisible(false);
        try {
            directa=new Conexion(bd);
        } catch (SQLException ex) {
            Logger.getLogger(WinPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ArchBaseActionPerformed

    private void BtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarClienteActionPerformed

    private void BtnBuscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarCliente1ActionPerformed

    private void TxtNdeFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNdeFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNdeFacturaActionPerformed

    private void BtnIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarClienteActionPerformed
        try{
           int ide=1;
           String idcliente=TxtCedula.getText();
           String nombrecliente=TxtNomCliente.getText();
           String apellidocliente=TxtApelCliente.getText();
           String fecha=TxtNacimiento.getText();
        }
    }//GEN-LAST:event_BtnIngresarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ArchBase;
    private javax.swing.JButton BtnActuaCliente;
    private javax.swing.JButton BtnActuaCliente1;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscarCliente;
    private javax.swing.JButton BtnBuscarCliente1;
    private javax.swing.JButton BtnBuscarFact;
    private javax.swing.JButton BtnBuscarVende;
    private javax.swing.JButton BtnEliminarClinete;
    private javax.swing.JButton BtnEliminarClinete1;
    private javax.swing.JButton BtnIngresarCliente;
    private javax.swing.JButton BtnIngresarCliente1;
    private javax.swing.JButton BtnModificarCliente;
    private javax.swing.JButton BtnModificarCliente1;
    private javax.swing.JMenuItem ItmAbrir;
    private javax.swing.JMenuItem ItmAcerca;
    private javax.swing.JMenuItem ItmLitsaVendedor;
    private javax.swing.JMenuItem ItmLstFacturas;
    private javax.swing.JMenuItem ItmNuevaFactura;
    private javax.swing.JMenuItem ItmNuevo;
    private javax.swing.JMenuItem ItmNuevoVendedor;
    private javax.swing.JMenuItem ItmRecorrer;
    private javax.swing.JMenuItem ItmSalir;
    private javax.swing.JMenu MnuDatos;
    private javax.swing.JPanel PnlCliente;
    private javax.swing.JPanel PnlFacturas;
    private javax.swing.JPanel PnlListaClientes;
    private javax.swing.JPanel PnlListaVendedor;
    private javax.swing.JPanel PnlListafacturas;
    private javax.swing.JPanel PnlVendedor;
    private javax.swing.JTable TblCliente;
    private javax.swing.JTable TblFacturas;
    private javax.swing.JTable TblVendedor;
    private javax.swing.JTextField TxtApelCliente;
    private javax.swing.JTextField TxtApelCliente1;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtCedula1;
    private javax.swing.JTextField TxtCelCliente;
    private javax.swing.JTextField TxtCelCliente1;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDireccion1;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtIdentificacion;
    private javax.swing.JTextField TxtIdentificacionVendedor;
    private javax.swing.JTextField TxtNacimiento;
    private javax.swing.JTextField TxtNdeFactura;
    private javax.swing.JTextField TxtNomCliente;
    private javax.swing.JTextField TxtNomCliente1;
    private javax.swing.JTextField TxtTelefCliente;
    private javax.swing.JTextField TxtTelefCliente1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
