/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterface;

import CapaDatos.*;
import java.awt.Color;
import java.io.File;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fredd
 */
public class WinFacturas extends javax.swing.JFrame {

    /**
     * Creates new form WinFacturas
     */
    ClsConexion base, cliente, producto, vende;
    String BasedeDatos;
    String nP,pP,uP,nC,aC,fC,dC,tC,cC,eC,nV,aV,dV,tV,cV,fFac,productoS,prod;
    int cP,clvP,clvC,clvV,clvCli,clvVen,clvFacS,cantidad,clvPS;
    public WinFacturas() throws SQLException {
        initComponents();
        ArchBd.setVisible(false);
        PnlProductos.setVisible(false);
        PnlClientes.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlCreFac.setVisible(false);
        PnlDetF.setVisible(false);
        this.setLocationRelativeTo(null);
        this.PnlProductos.setBackground(new Color(106,160,202));
        this.PnlClientes.setBackground(new Color(106,160,202));
        this.PnlVendedor.setBackground(new Color(106,160,202));
        this.PnlCreFac.setBackground(new Color(106,160,202));
        this.PnlDetF.setBackground(new Color(106,160,202));
        this.getContentPane().setBackground(new Color(106,160,202));
        //Crear un constructor
        TablaProductos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlProductos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNomPro = new javax.swing.JTextField();
        TxtPrecioPro = new javax.swing.JTextField();
        TxtCantPro = new javax.swing.JTextField();
        TxtUniPro = new javax.swing.JTextField();
        BtnSiguientePro = new javax.swing.JButton();
        BtnAnteriorPro = new javax.swing.JButton();
        LblRespPro = new javax.swing.JLabel();
        BrnNuevoPro = new javax.swing.JButton();
        BtnConsultaPro = new javax.swing.JButton();
        BtnActuaPro = new javax.swing.JButton();
        BtnEliminaPro = new javax.swing.JButton();
        BtnGuardarPro = new javax.swing.JButton();
        BtnGrabarPro = new javax.swing.JButton();
        BtnBorrarPro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        PnlClientes = new javax.swing.JPanel();
        BtnBorrarC = new javax.swing.JButton();
        BtnGrabarC = new javax.swing.JButton();
        BtnGuardarC = new javax.swing.JButton();
        BtnSiguienteC = new javax.swing.JButton();
        BtnAnteriorC = new javax.swing.JButton();
        BtnEliminarC = new javax.swing.JButton();
        BtnActuaC = new javax.swing.JButton();
        TxtDirC = new javax.swing.JTextField();
        TxtFecNC = new javax.swing.JTextField();
        TxtApellC = new javax.swing.JTextField();
        TxtNomC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnConsultaC = new javax.swing.JButton();
        BtnNuevoC = new javax.swing.JButton();
        LblRespC = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtTelC = new javax.swing.JTextField();
        TxtCelC = new javax.swing.JTextField();
        TxtEmailC = new javax.swing.JTextField();
        PnlVendedor = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TxtNomV = new javax.swing.JTextField();
        TxtApelV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtDirV = new javax.swing.JTextField();
        TxtTelV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtnCosultarV = new javax.swing.JButton();
        BtnNuevoV = new javax.swing.JButton();
        BtnActuaV = new javax.swing.JButton();
        BtnEliminaV = new javax.swing.JButton();
        LblRespV = new javax.swing.JLabel();
        BtnAnteriorV = new javax.swing.JButton();
        BtnSiguienteV = new javax.swing.JButton();
        BtnGuardarV = new javax.swing.JButton();
        BtnGrabarV = new javax.swing.JButton();
        BtnBorrarV = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        TxtCelV = new javax.swing.JTextField();
        ArchBd = new javax.swing.JFileChooser();
        PnlCreFac = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtEncFe = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CmbCodigoC = new javax.swing.JComboBox<>();
        CmbCodigoV = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        PnlDetF = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CmbProductos = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        TxtCanti = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        CmbFac = new javax.swing.JComboBox<>();
        TxtDisplay = new javax.swing.JTextField();
        BtnAceptarP = new javax.swing.JButton();
        BtnCarro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnBase = new javax.swing.JMenu();
        ItmAbrirBd = new javax.swing.JMenuItem();
        ItmSalir = new javax.swing.JMenuItem();
        MnProductos = new javax.swing.JMenu();
        ItmProducto = new javax.swing.JMenuItem();
        MnClientes = new javax.swing.JMenu();
        ItmClientes = new javax.swing.JMenuItem();
        MnVendedor = new javax.swing.JMenu();
        ItmVendedor = new javax.swing.JMenuItem();
        MnFactura = new javax.swing.JMenu();
        ItmNuevoF = new javax.swing.JMenuItem();
        ItmNF = new javax.swing.JMenuItem();
        ItmFacturas = new javax.swing.JMenuItem();
        MnAyuda = new javax.swing.JMenu();
        ItmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Sistema de Facturación");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cantidad del Producto:");
        jLabel3.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlProductos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 136, 169, 31));

        jLabel4.setText("Unidad del Producto:");
        jLabel4.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlProductos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 188, 169, 32));

        TxtNomPro.setEnabled(false);
        PnlProductos.add(TxtNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 45, 205, 31));

        TxtPrecioPro.setEnabled(false);
        PnlProductos.add(TxtPrecioPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 87, 205, 27));

        TxtCantPro.setEnabled(false);
        PnlProductos.add(TxtCantPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 132, 205, 35));

        TxtUniPro.setEnabled(false);
        PnlProductos.add(TxtUniPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 188, 205, 32));

        BtnSiguientePro.setText("Siguiente");
        BtnSiguientePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnSiguientePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        BtnAnteriorPro.setText("Anterior");
        BtnAnteriorPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnAnteriorPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));
        PnlProductos.add(LblRespPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 416, 31));

        BrnNuevoPro.setText("Nuevo");
        BrnNuevoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrnNuevoProActionPerformed(evt);
            }
        });
        PnlProductos.add(BrnNuevoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 79, -1));

        BtnConsultaPro.setText("Consultar");
        BtnConsultaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultaProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnConsultaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, -1, -1));

        BtnActuaPro.setText("Actualizar");
        BtnActuaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActuaProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnActuaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 87, -1, -1));

        BtnEliminaPro.setText("Eliminar");
        BtnEliminaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminaProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnEliminaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 173, 94, -1));

        BtnGuardarPro.setText("Guardar");
        BtnGuardarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnGuardarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 88, -1));

        BtnGrabarPro.setText("Modificar");
        BtnGrabarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnGrabarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 88, -1));

        BtnBorrarPro.setText("Borrar");
        BtnBorrarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarProActionPerformed(evt);
            }
        });
        PnlProductos.add(BtnBorrarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 88, -1));

        jLabel2.setText("Precio del Producto:");
        jLabel2.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 87, 169, 27));

        jLabel1.setText("Nombre del Producto:");
        PnlProductos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 45, 169, 31));

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaProductos);

        PnlProductos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 257, 540, 210));

        getContentPane().add(PnlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 800, 480));

        PnlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnBorrarC.setText("Borrar");
        BtnBorrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnBorrarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 464, 88, -1));

        BtnGrabarC.setText("Modificar");
        BtnGrabarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnGrabarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 430, 88, -1));

        BtnGuardarC.setText("Guardar");
        BtnGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnGuardarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 396, 88, -1));

        BtnSiguienteC.setText("Siguiente");
        BtnSiguienteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnSiguienteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 348, -1, -1));

        BtnAnteriorC.setText("Anterior");
        BtnAnteriorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnAnteriorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 348, -1, -1));

        BtnEliminarC.setText("Eliminar");
        BtnEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnEliminarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 265, 94, -1));

        BtnActuaC.setText("Actualizar");
        BtnActuaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActuaCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnActuaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 265, -1, -1));

        TxtDirC.setEnabled(false);
        PnlClientes.add(TxtDirC, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 199, 205, 32));

        TxtFecNC.setEnabled(false);
        PnlClientes.add(TxtFecNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 152, 205, 35));

        TxtApellC.setEnabled(false);
        PnlClientes.add(TxtApellC, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 110, 205, 27));

        TxtNomC.setEnabled(false);
        PnlClientes.add(TxtNomC, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 64, 205, 31));

        jLabel5.setText("Dirección del Cliente:");
        jLabel5.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlClientes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 199, 169, 32));

        jLabel6.setText("Fecha de Nacimiento:");
        jLabel6.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlClientes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 154, 169, 31));

        jLabel7.setText("Apellido del Cliente:");
        jLabel7.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlClientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 110, 169, 27));

        jLabel8.setText("Nombre del Cliente:");
        PnlClientes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 64, 169, 31));

        BtnConsultaC.setText("Consultar");
        BtnConsultaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultaCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnConsultaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 265, -1, -1));

        BtnNuevoC.setText("Nuevo");
        BtnNuevoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoCActionPerformed(evt);
            }
        });
        PnlClientes.add(BtnNuevoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 265, 79, -1));
        PnlClientes.add(LblRespC, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 299, 416, 31));

        jLabel9.setText("Telefono Convencional:");
        PnlClientes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 62, 177, 33));

        jLabel10.setText("Telefono Celular:");
        PnlClientes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 106, 177, 34));

        jLabel11.setText("Email:");
        PnlClientes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 152, 175, 35));

        TxtTelC.setEnabled(false);
        PnlClientes.add(TxtTelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 62, 192, 33));

        TxtCelC.setEnabled(false);
        PnlClientes.add(TxtCelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 106, 192, 34));

        TxtEmailC.setEnabled(false);
        PnlClientes.add(TxtEmailC, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 151, 192, 37));

        getContentPane().add(PnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        PnlVendedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Nombre del Vendedor:");
        PnlVendedor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 45, 169, 31));

        TxtNomV.setEnabled(false);
        PnlVendedor.add(TxtNomV, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 45, 205, 31));

        TxtApelV.setEnabled(false);
        PnlVendedor.add(TxtApelV, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 87, 205, 27));

        jLabel13.setText("Apellido del Vendedor:");
        jLabel13.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel13.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel13.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlVendedor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 87, 169, 27));

        TxtDirV.setEnabled(false);
        PnlVendedor.add(TxtDirV, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 132, 205, 35));

        TxtTelV.setEnabled(false);
        PnlVendedor.add(TxtTelV, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 178, 205, 32));

        jLabel14.setText("Telefono del Vendedor:");
        jLabel14.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel14.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel14.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlVendedor.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 178, 169, 32));

        jLabel15.setText("Dirección del Vendedor:");
        jLabel15.setMaximumSize(new java.awt.Dimension(104, 14));
        jLabel15.setMinimumSize(new java.awt.Dimension(104, 14));
        jLabel15.setPreferredSize(new java.awt.Dimension(104, 14));
        PnlVendedor.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 136, 169, 31));

        BtnCosultarV.setText("Consultar");
        BtnCosultarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCosultarVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnCosultarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, -1, -1));

        BtnNuevoV.setText("Nuevo");
        BtnNuevoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnNuevoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 79, -1));

        BtnActuaV.setText("Actualizar");
        BtnActuaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActuaVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnActuaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 91, 94, -1));

        BtnEliminaV.setText("Eliminar");
        BtnEliminaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminaVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnEliminaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 173, 94, -1));
        PnlVendedor.add(LblRespV, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 294, 416, 31));

        BtnAnteriorV.setText("Anterior");
        BtnAnteriorV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnAnteriorV, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 357, -1, -1));

        BtnSiguienteV.setText("Siguiente");
        BtnSiguienteV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnSiguienteV, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 357, -1, -1));

        BtnGuardarV.setText("Guardar");
        BtnGuardarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnGuardarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 398, 88, -1));

        BtnGrabarV.setText("Modificar");
        BtnGrabarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnGrabarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 427, 88, -1));

        BtnBorrarV.setText("Borrar");
        BtnBorrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarVActionPerformed(evt);
            }
        });
        PnlVendedor.add(BtnBorrarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 456, 88, -1));

        jLabel16.setText("Celular del Cliente:");
        PnlVendedor.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 221, 169, 35));

        TxtCelV.setEnabled(false);
        PnlVendedor.add(TxtCelV, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 221, 205, 35));

        getContentPane().add(PnlVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 830, 490));

        ArchBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchBdActionPerformed(evt);
            }
        });
        getContentPane().add(ArchBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        PnlCreFac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Codigo Cliente:");
        PnlCreFac.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 163, -1));

        jLabel18.setText("Codigo Vendedor:");
        PnlCreFac.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 155, 24));

        jLabel19.setText("Fecha:");
        PnlCreFac.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 141, 29));
        PnlCreFac.add(TxtEncFe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 230, 29));
        PnlCreFac.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 166, 131, 39));

        PnlCreFac.add(CmbCodigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 229, 35));

        PnlCreFac.add(CmbCodigoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 229, 30));

        jButton2.setText("Guardar Datos Factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PnlCreFac.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        getContentPane().add(PnlCreFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));

        jLabel22.setText("Detalles:");

        jLabel21.setText("Seleccione los Productos:");

        jLabel23.setText("Cantidad:");

        jLabel24.setText("Seleccione el codigo de la factura:");

        BtnAceptarP.setText("Aceptar");
        BtnAceptarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarPActionPerformed(evt);
            }
        });

        BtnCarro.setText("Añadir al Carrito");
        BtnCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlDetFLayout = new javax.swing.GroupLayout(PnlDetF);
        PnlDetF.setLayout(PnlDetFLayout);
        PnlDetFLayout.setHorizontalGroup(
            PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDetFLayout.createSequentialGroup()
                .addGroup(PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDetFLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlDetFLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(CmbFac, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlDetFLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCarro)
                        .addGap(203, 203, 203)))
                .addGroup(PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CmbProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtCanti, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlDetFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAceptarP)
                .addGap(161, 161, 161))
        );
        PnlDetFLayout.setVerticalGroup(
            PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDetFLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbFac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(CmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDetFLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlDetFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(PnlDetFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCanti, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarro))
                .addGap(41, 41, 41)
                .addComponent(BtnAceptarP)
                .addGap(130, 130, 130))
        );

        getContentPane().add(PnlDetF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 490));

        MnBase.setText("Base de Datos");

        ItmAbrirBd.setText("Abrir");
        ItmAbrirBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmAbrirBdActionPerformed(evt);
            }
        });
        MnBase.add(ItmAbrirBd);

        ItmSalir.setText("Salir");
        ItmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmSalirActionPerformed(evt);
            }
        });
        MnBase.add(ItmSalir);

        jMenuBar1.add(MnBase);

        MnProductos.setText("Productos");

        ItmProducto.setText("Consultar o Editar");
        ItmProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmProductoActionPerformed(evt);
            }
        });
        MnProductos.add(ItmProducto);

        jMenuBar1.add(MnProductos);

        MnClientes.setText("Clientes");

        ItmClientes.setText("Consultar y Editar");
        ItmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmClientesActionPerformed(evt);
            }
        });
        MnClientes.add(ItmClientes);

        jMenuBar1.add(MnClientes);

        MnVendedor.setText("Vendedor");

        ItmVendedor.setText("Consultar y Editar");
        ItmVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmVendedorActionPerformed(evt);
            }
        });
        MnVendedor.add(ItmVendedor);

        jMenuBar1.add(MnVendedor);

        MnFactura.setText("Factura");

        ItmNuevoF.setText("Nuevo Encabezado");
        ItmNuevoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmNuevoFActionPerformed(evt);
            }
        });
        MnFactura.add(ItmNuevoF);

        ItmNF.setText("Nueva Factura");
        ItmNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmNFActionPerformed(evt);
            }
        });
        MnFactura.add(ItmNF);

        ItmFacturas.setText("Consultar y Eliminar");
        ItmFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmFacturasActionPerformed(evt);
            }
        });
        MnFactura.add(ItmFacturas);

        jMenuBar1.add(MnFactura);

        MnAyuda.setText("Ayuda");

        ItmAcerca.setText("Acerca De");
        MnAyuda.add(ItmAcerca);

        jMenuBar1.add(MnAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItmFacturasActionPerformed

    private void ItmAbrirBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmAbrirBdActionPerformed
        // TODO add your handling code here:
        ArchBd.setVisible(true);
        PnlProductos.setVisible(false);
        PnlClientes.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlDetF.setVisible(false);
        PnlCreFac.setVisible(false);
    }//GEN-LAST:event_ItmAbrirBdActionPerformed

    private void ArchBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchBdActionPerformed
        // TODO add your handling code here:
        File f=ArchBd.getSelectedFile();
        BasedeDatos=f.getAbsolutePath();
        ArchBd.setVisible(false);
        try {
            base=new ClsConexion(BasedeDatos);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ArchBdActionPerformed

    private void ItmProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmProductoActionPerformed
        // TODO add your handling code here:
        TablaProductos.setVisible(true);
        try{
            DefaultTableModel model= new DefaultTableModel();
            TablaProductos.setModel(model);
            base.consulta1("TbProductos");
            ResultSetMetaData rsmd =base.getRegistros().getMetaData();
            int columnas= rsmd.getColumnCount();
            model.addColumn("Codigo");
            model.addColumn("Nombre");
            model.addColumn("Precio");
            model.addColumn("Stock");
            while(base.getRegistros().next()){
                Object [] filas= new Object[columnas];
                for (int i=0;i<columnas;i++){
                    filas[i]=base.getRegistros().getObject(i+1);
                }
                model.addRow(filas);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        BtnGuardarPro.setVisible(false);
        BtnGrabarPro.setVisible(false);
        BtnBorrarPro.setVisible(false);
        BtnAnteriorPro.setVisible(false);
        BtnSiguientePro.setVisible(false);
        PnlProductos.setVisible(true);
        PnlClientes.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlCreFac.setVisible(false);
        PnlDetF.setVisible(false);
        try {
            base.consulta("TbProducto");
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ItmProductoActionPerformed

    private void BtnAnteriorProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorProActionPerformed
        // TODO add your handling code here:
        
        try {
            base.anterior();
            TxtNomPro.setText(base.getRegistros().getString("nomProducto"));
            TxtPrecioPro.setText(base.getRegistros().getString("precioProducto"));
            TxtCantPro.setText(Integer.toString(base.getRegistros().getInt("cantProducto")));
            TxtUniPro.setText(base.getRegistros().getString("unidadProducto"));
            clvP=base.getRegistros().getInt("clvProducto");
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnAnteriorProActionPerformed

    private void BtnSiguienteProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteProActionPerformed
        // TODO add your handling code here:
                
        try {
            base.siguiente();
            TxtNomPro.setText(base.getRegistros().getString("nomProducto"));
            TxtPrecioPro.setText(base.getRegistros().getString("precioProducto"));
            TxtCantPro.setText(Integer.toString(base.getRegistros().getInt("cantProducto")));
            TxtUniPro.setText(base.getRegistros().getString("unidadProducto"));
            clvP=base.getRegistros().getInt("clvProducto");
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSiguienteProActionPerformed

    private void BtnConsultaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultaProActionPerformed
        // TODO add your handling code here:
        BtnSiguientePro.setVisible(true);
        BtnAnteriorPro.setVisible(true);
        BtnGuardarPro.setVisible(false);
        BtnGrabarPro.setVisible(false);
        BtnBorrarPro.setVisible(false);  
        LblRespPro.setText(null);
    }//GEN-LAST:event_BtnConsultaProActionPerformed

    private void BrnNuevoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrnNuevoProActionPerformed
        // TODO add your handling code here:
        BtnGuardarPro.setVisible(true);
        BtnGrabarPro.setVisible(false);
        BtnBorrarPro.setVisible(false);
        BtnAnteriorPro.setVisible(false);
        BtnSiguientePro.setVisible(false);     
        TxtNomPro.setEnabled(true);
        TxtPrecioPro.setEnabled(true);
        TxtCantPro.setEnabled(true);
        TxtUniPro.setEnabled(true);
        TxtNomPro.setText(null);
        TxtPrecioPro.setText(null);
        TxtCantPro.setText(null);
        TxtUniPro.setText(null);
        LblRespPro.setText(null);
    }//GEN-LAST:event_BrnNuevoProActionPerformed

    private void BtnActuaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActuaProActionPerformed
        // TODO add your handling code here:
        BtnGuardarPro.setVisible(false);
        BtnGrabarPro.setVisible(true);
        BtnBorrarPro.setVisible(false);    
        TxtNomPro.setEnabled(true);
        TxtPrecioPro.setEnabled(true);
        TxtCantPro.setEnabled(true);
        TxtUniPro.setEnabled(true); 
        LblRespPro.setText(null);
    }//GEN-LAST:event_BtnActuaProActionPerformed

    private void BtnEliminaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminaProActionPerformed
        // TODO add your handling code here:
        BtnGuardarPro.setVisible(false);
        BtnGrabarPro.setVisible(false);
        BtnBorrarPro.setVisible(true); 
        LblRespPro.setText(null);
    }//GEN-LAST:event_BtnEliminaProActionPerformed

    private void BtnGuardarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarProActionPerformed
        // TODO add your handling code here:
        nP=TxtNomPro.getText();
        pP=TxtPrecioPro.getText();
        cP=Integer.parseInt(TxtCantPro.getText());
        uP=TxtUniPro.getText();
        try {
            base.insertarP("TbProducto", nP, pP, cP, uP);
            LblRespPro.setText("***Registro Guardado Exitosamente***");
            TxtNomPro.setEnabled(false);
            TxtPrecioPro.setEnabled(false);
            TxtCantPro.setEnabled(false);
            TxtUniPro.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGuardarProActionPerformed

    private void BtnGrabarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarProActionPerformed
        nP=TxtNomPro.getText();
        pP=TxtPrecioPro.getText();
        cP=Integer.parseInt(TxtCantPro.getText());
        uP=TxtUniPro.getText();        
        try {
            base.modificarP("TbProducto", nP, pP, cP, uP, clvP);
            LblRespPro.setText("***El Registro se modifico exitosamente***");
            TxtNomPro.setEnabled(false);
            TxtPrecioPro.setEnabled(false);
            TxtCantPro.setEnabled(false);
            TxtUniPro.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGrabarProActionPerformed

    private void BtnBorrarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarProActionPerformed
        try {
            base.eliminarP("TbProducto", clvP);
            LblRespPro.setText("***Registro Eliminado Exitosamente***");        
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnBorrarProActionPerformed

    private void BtnBorrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarCActionPerformed
        // TODO add your handling code here:
        try {
            base.eliminarP("TbClientes", clvC);
            LblRespC.setText("***Registro Eliminado Exitosamente***");        
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BtnBorrarCActionPerformed

    private void BtnGrabarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarCActionPerformed
        // TODO add your handling code here:
        nC=TxtNomC.getText();
        aC=TxtApellC.getText();
        fC=TxtFecNC.getText();
        dC=TxtDirC.getText();
        tC=TxtTelC.getText();
        cC=TxtCelC.getText();
        eC=TxtEmailC.getText();
        try {
            base.actualizarC("TbClientes", nC, aC, fC, dC,tC,cC,eC, clvC);
            LblRespC.setText("***El Registro se modifico exitosamente***");
            TxtNomC.setEnabled(false);
            TxtApellC.setEnabled(false);
            TxtFecNC.setEnabled(false);
            TxtDirC.setEnabled(false);
            TxtTelC.setEnabled(false);
            TxtCelC.setEnabled(false);
            TxtEmailC.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BtnGrabarCActionPerformed

    private void BtnGuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarCActionPerformed
        // TODO add your handling code here:
        nC=TxtNomC.getText();
        aC=TxtApellC.getText();
        fC=TxtFecNC.getText();
        dC=TxtDirC.getText();
        tC=TxtTelC.getText();
        cC=TxtCelC.getText();
        eC=TxtEmailC.getText();
        try {
            base.insertarC("TbClientes", nC, aC, fC, dC,tC,cC,eC);
            LblRespC.setText("***Registro Guardado Exitosamente***");
            TxtNomC.setEnabled(false);
            TxtApellC.setEnabled(false);
            TxtFecNC.setEnabled(false);
            TxtDirC.setEnabled(false);
            TxtTelC.setEnabled(false);
            TxtCelC.setEnabled(false);
            TxtEmailC.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BtnGuardarCActionPerformed

    private void BtnSiguienteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteCActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            base.siguiente();
            TxtNomC.setText(base.getRegistros().getString("nomCliente"));
            TxtApellC.setText(base.getRegistros().getString("apellCliente"));
            TxtFecNC.setText(base.getRegistros().getString("fechanacCliente"));
            TxtDirC.setText(base.getRegistros().getString("dirCliente"));
            TxtTelC.setText(base.getRegistros().getString("telfCliente"));
            TxtCelC.setText(base.getRegistros().getString("celCliente"));
            TxtEmailC.setText(base.getRegistros().getString("emailCliente"));
            clvC=base.getRegistros().getInt("clvCliente");            
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BtnSiguienteCActionPerformed

    private void BtnAnteriorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorCActionPerformed
        try {
            // TODO add your handling code here:
            base.anterior();
            TxtNomC.setText(base.getRegistros().getString("nomCliente"));
            TxtApellC.setText(base.getRegistros().getString("apellCliente"));
            TxtFecNC.setText(base.getRegistros().getString("fechanacCliente"));
            TxtDirC.setText(base.getRegistros().getString("dirCliente"));
            TxtTelC.setText(base.getRegistros().getString("telfCliente"));
            TxtCelC.setText(base.getRegistros().getString("celCliente"));
            TxtEmailC.setText(base.getRegistros().getString("emailCliente"));
            clvC=base.getRegistros().getInt("clvCliente");            
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnAnteriorCActionPerformed

    private void BtnEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarCActionPerformed
        // TODO add your handling code here:
        BtnGuardarC.setVisible(false);
        BtnGrabarC.setVisible(false);
        BtnBorrarC.setVisible(true);
        BtnAnteriorC.setVisible(false);
        BtnSiguienteC.setVisible(false);    
        LblRespC.setText(null);
    }//GEN-LAST:event_BtnEliminarCActionPerformed

    private void BtnActuaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActuaCActionPerformed
        // TODO add your handling code here:
        BtnGuardarC.setVisible(false);
        BtnGrabarC.setVisible(true);
        BtnBorrarC.setVisible(false);
        BtnAnteriorC.setVisible(false);
        BtnSiguienteC.setVisible(false); 
        TxtNomC.setEnabled(true);
        TxtApellC.setEnabled(true);
        TxtFecNC.setEnabled(true);
        TxtDirC.setEnabled(true);
        TxtTelC.setEnabled(true);
        TxtCelC.setEnabled(true);
        TxtEmailC.setEnabled(true);
        LblRespC.setText(null);
    }//GEN-LAST:event_BtnActuaCActionPerformed

    private void BtnConsultaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultaCActionPerformed
        // TODO add your handling code here:
        BtnGuardarC.setVisible(false);
        BtnGrabarC.setVisible(false);
        BtnBorrarC.setVisible(false);
        BtnAnteriorC.setVisible(true);
        BtnSiguienteC.setVisible(true);  
        LblRespC.setText(null);
    }//GEN-LAST:event_BtnConsultaCActionPerformed

    private void BtnNuevoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoCActionPerformed
        // TODO add your handling code here:
        BtnGuardarC.setVisible(true);
        BtnGrabarC.setVisible(false);
        BtnBorrarC.setVisible(false);
        BtnAnteriorC.setVisible(false);
        BtnSiguienteC.setVisible(false);     
        TxtNomC.setEnabled(true);
        TxtApellC.setEnabled(true);
        TxtFecNC.setEnabled(true);
        TxtDirC.setEnabled(true);
        TxtTelC.setEnabled(true);
        TxtCelC.setEnabled(true);
        TxtEmailC.setEnabled(true);
        TxtNomC.setText(null);
        TxtApellC.setText(null);
        TxtFecNC.setText(null);
        TxtDirC.setText(null);
        TxtTelC.setText(null);
        TxtCelC.setText(null);
        TxtEmailC.setText(null);
        LblRespC.setText(null);        
    }//GEN-LAST:event_BtnNuevoCActionPerformed

    private void ItmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmClientesActionPerformed
        BtnAnteriorC.setVisible(false);
        BtnSiguienteC.setVisible(false);
        BtnGuardarC.setVisible(false);
        BtnGrabarC.setVisible(false);
        BtnBorrarC.setVisible(false);
        PnlClientes.setVisible(true);
        PnlProductos.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlDetF.setVisible(false);
        PnlCreFac.setVisible(false);
        try {
            // TODO add your handling code here:
            base.consulta("TbClientes");
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ItmClientesActionPerformed

    private void BtnCosultarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCosultarVActionPerformed
        // TODO add your handling code here:
        BtnGuardarV.setVisible(false);
        BtnGrabarV.setVisible(false);
        BtnBorrarV.setVisible(false);
        BtnAnteriorV.setVisible(true);
        BtnSiguienteV.setVisible(true);  
        LblRespV.setText(null);        
    }//GEN-LAST:event_BtnCosultarVActionPerformed

    private void BtnNuevoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoVActionPerformed
        // TODO add your handling code here:
        BtnGuardarV.setVisible(true);
        BtnGrabarV.setVisible(false);
        BtnBorrarV.setVisible(false);
        BtnAnteriorV.setVisible(false);
        BtnSiguienteV.setVisible(false);     
        TxtNomV.setEnabled(true);
        TxtApelV.setEnabled(true);
        TxtDirV.setEnabled(true);
        TxtTelV.setEnabled(true);
        TxtCelV.setEnabled(true);
        TxtNomV.setText(null);
        TxtApelV.setText(null);
        TxtDirV.setText(null);
        TxtTelV.setText(null);
        TxtCelV.setText(null);
        LblRespV.setText(null);      
    }//GEN-LAST:event_BtnNuevoVActionPerformed

    private void BtnActuaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActuaVActionPerformed
        // TODO add your handling code here:
        BtnGuardarV.setVisible(false);
        BtnGrabarV.setVisible(true);
        BtnBorrarV.setVisible(false);
        BtnAnteriorV.setVisible(false);
        BtnSiguienteV.setVisible(false);     
        TxtNomV.setEnabled(true);
        TxtApelV.setEnabled(true);
        TxtDirV.setEnabled(true);
        TxtTelV.setEnabled(true);
        TxtCelV.setEnabled(true); 
        LblRespV.setText(null); 
    }//GEN-LAST:event_BtnActuaVActionPerformed

    private void BtnEliminaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminaVActionPerformed
        // TODO add your handling code here:
        BtnGuardarV.setVisible(false);
        BtnGrabarV.setVisible(false);
        BtnBorrarV.setVisible(true);
        BtnAnteriorV.setVisible(false);
        BtnSiguienteV.setVisible(false);  
        LblRespV.setText(null);          
    }//GEN-LAST:event_BtnEliminaVActionPerformed

    private void BtnAnteriorVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorVActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            base.anterior();
            TxtNomV.setText(base.getRegistros().getString("nomVendedor"));
            TxtApelV.setText(base.getRegistros().getString("apellVendedor"));
            TxtDirV.setText(base.getRegistros().getString("dirVendedor"));
            TxtTelV.setText(base.getRegistros().getString("tlfVendedor"));
            TxtCelV.setText(base.getRegistros().getString("celVendedor"));
            clvV=base.getRegistros().getInt("clvVendedor");            
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAnteriorVActionPerformed

    private void BtnSiguienteVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteVActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            base.siguiente();
            TxtNomV.setText(base.getRegistros().getString("nomVendedor"));
            TxtApelV.setText(base.getRegistros().getString("apellVendedor"));
            TxtDirV.setText(base.getRegistros().getString("dirVendedor"));
            TxtTelV.setText(base.getRegistros().getString("tlfVendedor"));
            TxtCelV.setText(base.getRegistros().getString("celVendedor"));
            clvV=base.getRegistros().getInt("clvVendedor");            
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BtnSiguienteVActionPerformed

    private void BtnGuardarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarVActionPerformed
        // TODO add your handling code here:
        nV=TxtNomV.getText();
        aV=TxtApelV.getText();
        dV=TxtDirV.getText();
        tV=TxtTelV.getText();
        cV=TxtCelV.getText();
        try {
            base.insertarV("TbVendedor", nV, aV, dV,tV,cV);
            LblRespV.setText("***Registro Guardado Exitosamente***");
            TxtNomV.setEnabled(false);
            TxtApelV.setEnabled(false);
            TxtDirV.setEnabled(false);
            TxtTelV.setEnabled(false);
            TxtCelV.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }//GEN-LAST:event_BtnGuardarVActionPerformed

    private void BtnGrabarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarVActionPerformed
        // TODO add your handling code here:
        nV=TxtNomV.getText();
        aV=TxtApelV.getText();
        dV=TxtDirV.getText();
        tV=TxtTelV.getText();
        cV=TxtCelV.getText();
        try {
            base.actualizarV("TbVendedor", nV, aV, dV,tV,cV, clvV);
            LblRespV.setText("***El Registro se modifico exitosamente***");
            TxtNomV.setEnabled(false);
            TxtApelV.setEnabled(false);
            TxtDirV.setEnabled(false);
            TxtTelV.setEnabled(false);
            TxtCelV.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_BtnGrabarVActionPerformed

    private void BtnBorrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarVActionPerformed
        // TODO add your handling code here:
        try {
            base.eliminarV("TbVendedor", clvV);
            LblRespV.setText("***Registro Eliminado Exitosamente***");          
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }//GEN-LAST:event_BtnBorrarVActionPerformed

    private void ItmVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmVendedorActionPerformed
        // TODO add your handling code here:
        BtnGuardarV.setVisible(false);
        BtnGrabarV.setVisible(false);
        BtnBorrarV.setVisible(false);
        BtnAnteriorV.setVisible(false);
        BtnSiguienteV.setVisible(false); 
        PnlClientes.setVisible(false);
        PnlProductos.setVisible(false);
        PnlVendedor.setVisible(true);
        PnlDetF.setVisible(false);
        PnlCreFac.setVisible(false);
        try {
            base.consulta("TbVendedor");
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ItmVendedorActionPerformed

    private void ItmNuevoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmNuevoFActionPerformed
        // TODO add your handling code here:
        PnlCreFac.setVisible(true);
        PnlVendedor.setVisible(false);
        PnlProductos.setVisible(false);
        PnlClientes.setVisible(false);
        PnlDetF.setVisible(false);
        cliente=base;
        vende=base;
        try{
            ArrayList<String> listacli= new ArrayList<>();
            listacli=cliente.llenarclientes();
            for(int i=0; i<listacli.size();i++){
                CmbCodigoC.addItem(listacli.get(i));
            }
            ArrayList<String> listavende= new ArrayList<>();
            listavende=vende.llenarvende();
            for(int i=0; i<listavende.size();i++){
                CmbCodigoV.addItem(listavende.get(i));
            }         
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ItmNuevoFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clvCli=Integer.parseInt((String) CmbCodigoC.getSelectedItem());
        clvVen=Integer.parseInt((String) CmbCodigoV.getSelectedItem());
        fFac=TxtEncFe.getText();
        PnlCreFac.setVisible(false);
        try {
            base.insertarCabF(fFac, clvCli, clvVen);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ItmNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmNFActionPerformed
        // TODO add your handling code here:
        PnlDetF.setVisible(true);
        PnlProductos.setVisible(false);
        PnlClientes.setVisible(false);
        PnlVendedor.setVisible(false);
        PnlCreFac.setVisible(false);
        producto=base;
        try {
            ArrayList<String> listaf= new ArrayList<>();
            listaf=base.llenarDet();
            for(int i=0; i<listaf.size();i++){
                CmbFac.addItem(listaf.get(i));
            }  
            ArrayList<String> listapro= new ArrayList<>();
            listapro=producto.llenarPro();
            for(int i=0; i<listapro.size();i++){
                CmbProductos.addItem(listapro.get(i));
            }                 
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    }//GEN-LAST:event_ItmNFActionPerformed

    private void BtnAceptarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarPActionPerformed
        // TODO add your handling code here:
        prod=(String) CmbProductos.getSelectedItem();
        String[] clave=prod.split(",");
        clvPS=Integer.parseInt(clave[0]);
        clvFacS= Integer.parseInt((String)CmbFac.getSelectedItem());
        cantidad=Integer.parseInt(TxtCanti.getText());
        TxtDisplay.setText(cantidad+"    "+clave[1]);
    }//GEN-LAST:event_BtnAceptarPActionPerformed

    private void BtnCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarroActionPerformed
        try {
            // TODO add your handling code here:
            base.GuardaDet(clvFacS,clvPS , cantidad);
            int cant=base.RetornaCantidad(clvPS);
            int ncant=cant-cantidad;
            producto.RestaPro(ncant, clvPS);
        } catch (SQLException ex) {
            Logger.getLogger(WinFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnCarroActionPerformed

    private void ItmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ArchBd;
    private javax.swing.JButton BrnNuevoPro;
    private javax.swing.JButton BtnAceptarP;
    private javax.swing.JButton BtnActuaC;
    private javax.swing.JButton BtnActuaPro;
    private javax.swing.JButton BtnActuaV;
    private javax.swing.JButton BtnAnteriorC;
    private javax.swing.JButton BtnAnteriorPro;
    private javax.swing.JButton BtnAnteriorV;
    private javax.swing.JButton BtnBorrarC;
    private javax.swing.JButton BtnBorrarPro;
    private javax.swing.JButton BtnBorrarV;
    private javax.swing.JButton BtnCarro;
    private javax.swing.JButton BtnConsultaC;
    private javax.swing.JButton BtnConsultaPro;
    private javax.swing.JButton BtnCosultarV;
    private javax.swing.JButton BtnEliminaPro;
    private javax.swing.JButton BtnEliminaV;
    private javax.swing.JButton BtnEliminarC;
    private javax.swing.JButton BtnGrabarC;
    private javax.swing.JButton BtnGrabarPro;
    private javax.swing.JButton BtnGrabarV;
    private javax.swing.JButton BtnGuardarC;
    private javax.swing.JButton BtnGuardarPro;
    private javax.swing.JButton BtnGuardarV;
    private javax.swing.JButton BtnNuevoC;
    private javax.swing.JButton BtnNuevoV;
    private javax.swing.JButton BtnSiguienteC;
    private javax.swing.JButton BtnSiguientePro;
    private javax.swing.JButton BtnSiguienteV;
    private javax.swing.JComboBox<String> CmbCodigoC;
    private javax.swing.JComboBox<String> CmbCodigoV;
    private javax.swing.JComboBox<String> CmbFac;
    private javax.swing.JComboBox<String> CmbProductos;
    private javax.swing.JMenuItem ItmAbrirBd;
    private javax.swing.JMenuItem ItmAcerca;
    private javax.swing.JMenuItem ItmClientes;
    private javax.swing.JMenuItem ItmFacturas;
    private javax.swing.JMenuItem ItmNF;
    private javax.swing.JMenuItem ItmNuevoF;
    private javax.swing.JMenuItem ItmProducto;
    private javax.swing.JMenuItem ItmSalir;
    private javax.swing.JMenuItem ItmVendedor;
    private javax.swing.JLabel LblRespC;
    private javax.swing.JLabel LblRespPro;
    private javax.swing.JLabel LblRespV;
    private javax.swing.JMenu MnAyuda;
    private javax.swing.JMenu MnBase;
    private javax.swing.JMenu MnClientes;
    private javax.swing.JMenu MnFactura;
    private javax.swing.JMenu MnProductos;
    private javax.swing.JMenu MnVendedor;
    private javax.swing.JPanel PnlClientes;
    private javax.swing.JPanel PnlCreFac;
    private javax.swing.JPanel PnlDetF;
    private javax.swing.JPanel PnlProductos;
    private javax.swing.JPanel PnlVendedor;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTextField TxtApelV;
    private javax.swing.JTextField TxtApellC;
    private javax.swing.JTextField TxtCantPro;
    private javax.swing.JTextField TxtCanti;
    private javax.swing.JTextField TxtCelC;
    private javax.swing.JTextField TxtCelV;
    private javax.swing.JTextField TxtDirC;
    private javax.swing.JTextField TxtDirV;
    private javax.swing.JTextField TxtDisplay;
    private javax.swing.JTextField TxtEmailC;
    private javax.swing.JTextField TxtEncFe;
    private javax.swing.JTextField TxtFecNC;
    private javax.swing.JTextField TxtNomC;
    private javax.swing.JTextField TxtNomPro;
    private javax.swing.JTextField TxtNomV;
    private javax.swing.JTextField TxtPrecioPro;
    private javax.swing.JTextField TxtTelC;
    private javax.swing.JTextField TxtTelV;
    private javax.swing.JTextField TxtUniPro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
