/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;
import CapaNegocio.*;
/**
 *
 * @author Usuario
 */
public class WinFraccion extends javax.swing.JFrame {
    int num,den,codigo;
    ClsFraccion A,B;
    
    /**
     * Creates new form WinFraccion
     */
    public WinFraccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        TxtDisplay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnDen = new javax.swing.JButton();
        BtnSuma = new javax.swing.JButton();
        BtnNum = new javax.swing.JButton();
        BtnResta = new javax.swing.JButton();
        BtnMul = new javax.swing.JButton();
        BtnDividir = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnSimplificar = new javax.swing.JButton();
        BtnValor = new javax.swing.JButton();
        BtnSlair = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton8.setText("/");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtDisplay.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel1.setText("Autor: Marvin Zambrano V1.01");

        BtnDen.setText("Denominador");
        BtnDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDenActionPerformed(evt);
            }
        });

        BtnSuma.setText("+");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        BtnNum.setText("Numerador");
        BtnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNumActionPerformed(evt);
            }
        });

        BtnResta.setText("-");
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });

        BtnMul.setText("*");
        BtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMulActionPerformed(evt);
            }
        });

        BtnDividir.setText("/");
        BtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDividirActionPerformed(evt);
            }
        });

        BtnIgual.setText("=");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnSimplificar.setText("Simplificar");
        BtnSimplificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimplificarActionPerformed(evt);
            }
        });

        BtnValor.setText("Valor Decimal");
        BtnValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValorActionPerformed(evt);
            }
        });

        BtnSlair.setText("Salir");
        BtnSlair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSlairActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtDisplay)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(BtnNum))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtnSlair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnLimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDen)
                    .addComponent(jLabel1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(BtnSuma)
                .addGap(18, 18, 18)
                .addComponent(BtnResta)
                .addGap(18, 18, 18)
                .addComponent(BtnMul)
                .addGap(18, 18, 18)
                .addComponent(BtnDividir)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(BtnIgual))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(BtnSimplificar)
                        .addGap(57, 57, 57)
                        .addComponent(BtnValor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDen)
                    .addComponent(BtnNum))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSuma)
                    .addComponent(BtnResta)
                    .addComponent(BtnMul)
                    .addComponent(BtnDividir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BtnIgual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSimplificar)
                            .addComponent(BtnValor))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSlair)
                            .addComponent(BtnLimpiar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNumActionPerformed
        num=Integer.parseInt(TxtDisplay.getText());
        BtnNum.setEnabled(false);
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnNumActionPerformed

    private void BtnDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDenActionPerformed
        den=Integer.parseInt(TxtDisplay.getText());
        BtnNum.setEnabled(true);
        B=new ClsFraccion(num,den);
        TxtDisplay.setText(B.Resultado());
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnDenActionPerformed

    private void BtnSimplificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimplificarActionPerformed
        B.simplificar();
        TxtDisplay.setText(B.Resultado());
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnSimplificarActionPerformed

    private void BtnValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValorActionPerformed
        TxtDisplay.setText(String.valueOf(B.valor()));
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnValorActionPerformed

    private void BtnSlairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSlairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSlairActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        A=new ClsFraccion(B);
        codigo=1;
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        A=new ClsFraccion(B);
        codigo=2;
    }//GEN-LAST:event_BtnRestaActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        switch (codigo){
            case 1:
            {
                B=A.suma(B);
                break;
            }
            case 2:
            {
                B=A.resta(B);
                break;
            } 
            case 3:
            {
                B=A.multiplicacion(B);
                break;
            }
            case 4:
            {
                B=A.division(B);
                break;
            }
        }
        TxtDisplay.setText(B.Resultado());
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDividirActionPerformed
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        A=new ClsFraccion(B);
        codigo=4;
    }//GEN-LAST:event_BtnDividirActionPerformed

    private void BtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMulActionPerformed
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        A=new ClsFraccion(B);
        codigo=3;
    }//GEN-LAST:event_BtnMulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinFraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinFraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinFraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinFraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinFraccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDen;
    private javax.swing.JButton BtnDividir;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnMul;
    private javax.swing.JButton BtnNum;
    private javax.swing.JButton BtnResta;
    private javax.swing.JButton BtnSimplificar;
    private javax.swing.JButton BtnSlair;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JButton BtnValor;
    private javax.swing.JTextField TxtDisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
