/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaBase.CtrProducto;
import CapaModelo.ClsConexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SANTI
 */
public final class Winmujer extends javax.swing.JFrame {

    DefaultTableModel contactos = new DefaultTableModel();
    ClsConexion clte;
    CtrProducto list = new CtrProducto();

    /**
     * Creates new form WinTablaGatos
     */
    public Winmujer() {
        initComponents();
        llenarTabla();
    }

    public void limpiarTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) TblProductos.getModel();
            int filas = TblProductos.getRowCount();
            for (int i = 0; i <= filas; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

    public void llenarTabla() {
        limpiarTabla();
        clte = new ClsConexion("C://Users//JONATHAN Y LUIS//Desktop//PryProyectoFinal//DBProyecto.accdb");
        try {
            ResultSet tlf;
            tlf = clte.listaProducto("mujer");
            while (contactos.getRowCount() > 0) {
                contactos.removeRow(0);
            }
            list.llenarTabla(contactos, tlf);

        } catch (SQLException ex) {
            Logger.getLogger(WinRegistroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ResultSet rs = clte.aviso("mujer");
            list.aviso(rs);
        } catch (SQLException ex) {
            Logger.getLogger(Winhombrre.class.getName()).log(Level.SEVERE, null, ex);
        }
        TblProductos.setModel(contactos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblProductos = new javax.swing.JTable();
        BtnGuardarCambios = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TblProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblProductos);

        BtnGuardarCambios.setBackground(new java.awt.Color(0, 0, 0));
        BtnGuardarCambios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnGuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarCambios.setText("GUARDAR CAMBIOS");
        BtnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarCambiosActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("ELIMINAR ");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnSalir2.setBackground(new java.awt.Color(102, 102, 102));
        BtnSalir2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSalir2.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir2.setText("SALIR");
        BtnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarCambios)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnSalir2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarCambiosActionPerformed
        int Fila = TblProductos.getSelectedRow();
        int id = Integer.parseInt(TblProductos.getValueAt(Fila, 0).toString());
        String nombre = TblProductos.getValueAt(Fila, 1).toString();
        String tipo = TblProductos.getValueAt(Fila, 2).toString();
        Double precio = Double.parseDouble(TblProductos.getValueAt(Fila, 3).toString());
        int cantidad = Integer.parseInt(TblProductos.getValueAt(Fila, 4).toString());
        list.modificar(nombre, tipo, precio, cantidad, id);
        llenarTabla();
    }//GEN-LAST:event_BtnGuardarCambiosActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int Fila = TblProductos.getSelectedRow();
        int codigo = Integer.parseInt(TblProductos.getValueAt(Fila, 0).toString());
        list.borrar(codigo);
        llenarTabla();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Winmujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Winmujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Winmujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Winmujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Winmujer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardarCambios;
    private javax.swing.JButton BtnSalir2;
    private javax.swing.JTable TblProductos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
