/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
public class DlgSobre extends java.awt.Dialog {

    /**
     * Creates new form DlgSobre
     */
    public DlgSobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JPanelImagen pf = new JPanelImagen();
        pf.setIcon(new ImageIcon(this.getClass().getResource("/IMAGENES/logoapr.png")));
        pf.setPreferredSize(new Dimension(300,200));
        this.add(pf, BorderLayout.WEST);
        this.setSize(new Dimension(700,390));
        this.setLocationRelativeTo(parent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setAlwaysOnTop(true);
        setLocationRelativeTo(null);
        setModal(true);
        setResizable(false);
        setTitle("Sobre Facturacion APR");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 150));

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <h1>Nota</h1>\n    <p style=\"margin-top: 0\">\r\n      \rEste ejemplo esta basado en el diseño de autor desconocido.\n      Este ejemplo es una version mejorada, en la cual se utiliza el patrón de diseño MVC(Modelo - Vista - Controlador).\t\n    </p>\r\n    <h3 style=\"font-weidth:bold;\">Enlaces</h3>\n    <ul>\n      <li>Página Web:<a href=\"http://www.elaprendiz.net63.net\">www.elaprendiz.net63.net</a></li>\n       <li>Blog:<a href=\"http://www.javanoesdificil.blogspot.com\">www.javanoesdificil.blogspot.com</a></li>\n <li>Blog:<a href=\"http://www.minisistemas.blogspot.com\">www.minisistemas.blogspot.com</a></li>\t\n<li>Canal Youtube:<a href=\"http://www.youtube.com/user/jleod7\">http://www.youtube.com/user/jleod7</a></li>\n<li>FaceBook:<a href=\"http://www.facebook.com/elaprendiz.net63.net\">http://www.facebook.com/elaprendiz.net63.net</a></li>\n<li>Twitter:<a href=\"http://www.Twitter.com/jleod7\">http://www.Twitter.com/jleod7</a></li>\t\t\t\n    <ul/>\n  </body>\r\n</html>\r\n");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      setVisible(false);
      dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
