package ventanas;

import controller.FacturaController;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelobd.Articulo;
import modelobd.Cliente;
import modelobd.VFactura;
import modelobd.Vendedor;
import modelogui.ModeloDetalleVentaArticulo;
import modelogui.ModeloTablaArticulo;
import utilidades.ExaminadorCampos;
import utilidades.Helper;

/**
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
public class JFacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFacturas
     */
    ModeloTablaArticulo mta;
    ModeloDetalleVentaArticulo mdva;
    private VFactura factura;
    private Articulo art;
    private FacturaController fc = new FacturaController();
    private Cliente cliente;
    private Vendedor vendedor;
    private int cancelado = -1;
    private double subTotal = 0.0;
    private double descuento = 0.0;
    private double iva = 0.0;
    private double total = 0.0; 
    private int posicionRegistro = 0;
    public JFacturas() {
        initComponents();        
        factura = fc.getUltimaFactura();        
        mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
        tblProductos.setModel(mdva);
        tblProductos.setRowSelectionAllowed(true);
        tblProductos.setAutoscrolls(true);
        posicionRegistro = fc.getNumFacturas();
        cargarDatos();
        cargarEventos();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bntPrimero = new javax.swing.JButton();
        bntAnterior = new javax.swing.JButton();
        bntBuscar = new javax.swing.JButton();
        bntSig = new javax.swing.JButton();
        bntUltimo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dcFechaEmision = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        pnlBotonesEdicion = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        bntCalculladora = new javax.swing.JButton();
        bntAgregarProducto = new javax.swing.JButton();
        bntQuitar = new javax.swing.JButton();
        bntModificarCantidad = new javax.swing.JButton();
        bntSalir = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        pnlCantidades = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaObservacion = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        pnlBotonesPrincipal = new javax.swing.JPanel();
        bntNuevo = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();
        bntguardar = new javax.swing.JButton();
        bntGuardaImprimir = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtPagoInicial = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        pnlEntradas = new javax.swing.JPanel();
        pnlEntradas2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbVendedor = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmbFormaPago = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtPorcentajeDescuento = new javax.swing.JTextField();
        pnlEntradas1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        bntRClientes = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Venta de Productos");
        setToolTipText("");
        setVisible(true);
        getContentPane().setLayout(new java.awt.BorderLayout(4, 2));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        bntPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PRIMERO.JPG"))); // NOI18N
        bntPrimero.setToolTipText("Primero");
        jPanel3.add(bntPrimero);

        bntAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ANTERIOR.JPG"))); // NOI18N
        bntAnterior.setToolTipText("Anterior");
        jPanel3.add(bntAnterior);

        bntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/BUSCAR.JPG"))); // NOI18N
        bntBuscar.setToolTipText("Buscar Factura");
        jPanel3.add(bntBuscar);

        bntSig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/SIGUIENTE.JPG"))); // NOI18N
        bntSig.setToolTipText("Siguiente");
        jPanel3.add(bntSig);

        bntUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ULTIMO.JPG"))); // NOI18N
        bntUltimo.setToolTipText("Ultimo");
        jPanel3.add(bntUltimo);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Factura de Venta Número: ");
        jPanel5.add(jLabel1);

        txtNumFactura.setEditable(false);
        txtNumFactura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumFactura.setText("00000");
        txtNumFactura.setPreferredSize(new java.awt.Dimension(80, 21));
        jPanel5.add(txtNumFactura);

        jPanel4.add(jPanel5);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Fecha de Emisión: ");
        jPanel6.add(jLabel2);

        dcFechaEmision.setDateFormatString("dd/MM/yyyy");
        dcFechaEmision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dcFechaEmision.setPreferredSize(new java.awt.Dimension(95, 20));
        jPanel6.add(dcFechaEmision);

        jPanel4.add(jPanel6);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlBotonesEdicion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBotonesEdicion.setLayout(new java.awt.GridLayout(6, 1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/GENTE.JPG"))); // NOI18N
        jButton7.setToolTipText("Ingresar Nuevo Cliente");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnlBotonesEdicion.add(jButton7);

        bntCalculladora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CALCULADORA.JPG"))); // NOI18N
        bntCalculladora.setToolTipText("Calculadora");
        bntCalculladora.setEnabled(false);
        pnlBotonesEdicion.add(bntCalculladora);

        bntAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/INSERTAR.JPG"))); // NOI18N
        bntAgregarProducto.setToolTipText("InserTar Producto En La Factura");
        bntAgregarProducto.setEnabled(false);
        bntAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarProductoActionPerformed(evt);
            }
        });
        pnlBotonesEdicion.add(bntAgregarProducto);

        bntQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ELIMINAR.JPG"))); // NOI18N
        bntQuitar.setToolTipText("Quitar Producto De La Factura");
        bntQuitar.setEnabled(false);
        bntQuitar.setName("bntQuitar"); // NOI18N
        pnlBotonesEdicion.add(bntQuitar);

        bntModificarCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MODIFICAR.JPG"))); // NOI18N
        bntModificarCantidad.setToolTipText("Modificar Cantidad");
        bntModificarCantidad.setEnabled(false);
        bntModificarCantidad.setName("bntCantidad"); // NOI18N
        pnlBotonesEdicion.add(bntModificarCantidad);

        bntSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/SALIR.JPG"))); // NOI18N
        bntSalir.setToolTipText("Salir");
        pnlBotonesEdicion.add(bntSalir);

        jPanel2.add(pnlBotonesEdicion, java.awt.BorderLayout.LINE_END);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new java.awt.BorderLayout());

        pnlCantidades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCantidades.setLayout(new javax.swing.BoxLayout(pnlCantidades, javax.swing.BoxLayout.LINE_AXIS));

        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setText("Observación: ");
        jPanel23.add(jLabel11);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(166, 52));

        txtAreaObservacion.setColumns(20);
        txtAreaObservacion.setRows(5);
        txtAreaObservacion.setPreferredSize(new java.awt.Dimension(164, 50));
        jScrollPane3.setViewportView(txtAreaObservacion);

        jPanel23.add(jScrollPane3);

        jPanel21.add(jPanel23);

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.LINE_AXIS));

        pnlBotonesPrincipal.setLayout(new java.awt.GridLayout(1, 5));

        bntNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/NUEVO.JPG"))); // NOI18N
        bntNuevo.setToolTipText("Nueva Factura");
        bntNuevo.setName("bntN"); // NOI18N
        bntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoActionPerformed(evt);
            }
        });
        pnlBotonesPrincipal.add(bntNuevo);

        bntEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CANCELAR2.JPG"))); // NOI18N
        bntEliminar.setToolTipText("Anular Factura");
        bntEliminar.setName("bntE"); // NOI18N
        pnlBotonesPrincipal.add(bntEliminar);

        bntguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/GUARDAR2.JPG"))); // NOI18N
        bntguardar.setToolTipText("Guardar");
        bntguardar.setEnabled(false);
        pnlBotonesPrincipal.add(bntguardar);

        bntGuardaImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/GUARDAR2.JPG"))); // NOI18N
        bntGuardaImprimir.setToolTipText("Guardar/Imprimir ");
        bntGuardaImprimir.setEnabled(false);
        pnlBotonesPrincipal.add(bntGuardaImprimir);

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CANCELAR.JPG"))); // NOI18N
        bntCancelar.setToolTipText("Cancelar");
        bntCancelar.setEnabled(false);
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });
        pnlBotonesPrincipal.add(bntCancelar);

        jPanel24.add(pnlBotonesPrincipal);

        jPanel26.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Pago Inicial: ");
        jLabel12.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        jPanel26.add(jLabel12, gridBagConstraints);

        txtPagoInicial.setEditable(false);
        txtPagoInicial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPagoInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPagoInicial.setText("0.0");
        txtPagoInicial.setPreferredSize(new java.awt.Dimension(70, 21));
        jPanel26.add(txtPagoInicial, new java.awt.GridBagConstraints());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Saldo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        jPanel26.add(jLabel13, gridBagConstraints);

        txtSaldo.setEditable(false);
        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSaldo.setText("0.0");
        txtSaldo.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel26.add(txtSaldo, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Factura Procesada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        jPanel26.add(jLabel14, gridBagConstraints);

        jPanel24.add(jPanel26);

        jPanel21.add(jPanel24);

        pnlCantidades.add(jPanel21);

        jPanel22.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("SubTotal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 4);
        jPanel22.add(jLabel10, gridBagConstraints);

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubtotal.setText("0.0");
        txtSubtotal.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel22.add(txtSubtotal, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Total Desc.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 4);
        jPanel22.add(jLabel15, gridBagConstraints);

        txtDescuento.setEditable(false);
        txtDescuento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDescuento.setText("0.0");
        txtDescuento.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel22.add(txtDescuento, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Total IVA.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 4);
        jPanel22.add(jLabel16, gridBagConstraints);

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIva.setText("0.0");
        txtIva.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel22.add(txtIva, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 255));
        jLabel17.setText("TOTAL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel22.add(jLabel17, gridBagConstraints);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(102, 153, 255));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("0.0");
        txtTotal.setPreferredSize(new java.awt.Dimension(80, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel22.add(txtTotal, gridBagConstraints);

        pnlCantidades.add(jPanel22);

        jPanel8.add(pnlCantidades, java.awt.BorderLayout.PAGE_END);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.PAGE_AXIS));

        pnlEntradas.setLayout(new java.awt.BorderLayout(4, 4));

        pnlEntradas2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Célula/RUC:");
        jLabel5.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        pnlEntradas2.add(jLabel5, gridBagConstraints);

        txtRuc.setEditable(false);
        txtRuc.setPreferredSize(new java.awt.Dimension(185, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 2;
        pnlEntradas2.add(txtRuc, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Telefóno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 32, 0, 0);
        pnlEntradas2.add(jLabel6, gridBagConstraints);

        txtTelefono.setEditable(false);
        txtTelefono.setPreferredSize(new java.awt.Dimension(195, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 2;
        pnlEntradas2.add(txtTelefono, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Vendedor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 6, 1);
        pnlEntradas2.add(jLabel7, gridBagConstraints);

        cmbVendedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbVendedor.setModel(new DefaultComboBoxModel(FacturaController.getCliente()));
        cmbVendedor.setPreferredSize(new java.awt.Dimension(470, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        pnlEntradas2.add(cmbVendedor, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Forma de Pago:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        pnlEntradas2.add(jLabel8, gridBagConstraints);

        cmbFormaPago.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbFormaPago.setModel(new DefaultComboBoxModel(VFactura.tipoPago));
        cmbFormaPago.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 2;
        pnlEntradas2.add(cmbFormaPago, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Descuento %:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 6, 0);
        pnlEntradas2.add(jLabel9, gridBagConstraints);

        txtPorcentajeDescuento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPorcentajeDescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPorcentajeDescuento.setText("0");
        txtPorcentajeDescuento.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        pnlEntradas2.add(txtPorcentajeDescuento, gridBagConstraints);

        pnlEntradas.add(pnlEntradas2, java.awt.BorderLayout.CENTER);

        pnlEntradas1.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.BorderLayout());

        bntRClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/GENTES.JPG"))); // NOI18N
        bntRClientes.setToolTipText("Buscar Clientes");
        bntRClientes.setEnabled(false);
        bntRClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRClientesActionPerformed(evt);
            }
        });
        jPanel15.add(bntRClientes, java.awt.BorderLayout.CENTER);

        pnlEntradas1.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel16.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cliente: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel16.add(jLabel3, gridBagConstraints);

        txtCliente.setEditable(false);
        txtCliente.setPreferredSize(new java.awt.Dimension(520, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel16.add(txtCliente, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel16.add(jLabel4, gridBagConstraints);

        txtDireccion.setEditable(false);
        txtDireccion.setPreferredSize(new java.awt.Dimension(520, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel16.add(txtDireccion, gridBagConstraints);

        pnlEntradas1.add(jPanel16, java.awt.BorderLayout.WEST);

        pnlEntradas.add(pnlEntradas1, java.awt.BorderLayout.PAGE_START);

        jPanel10.add(pnlEntradas);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 120));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblProductosFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel12.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel12);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRClientesActionPerformed
       PanelVistaCliente pvc = new PanelVistaCliente();
       JLabel aviso = new JLabel("Doble click para seleccionar");
        aviso.setEnabled(false); 
        aviso.setOpaque(true);
        JOptionPane.showInternalOptionDialog(this, pvc, "Seleccione un Cliente",JOptionPane.OK_CANCEL_OPTION,
                                            JOptionPane.QUESTION_MESSAGE, null, new Object[]{aviso},null);
      if(pvc.getCl() != null){
          setCliente(pvc.getCl());
      }
    }//GEN-LAST:event_bntRClientesActionPerformed

    private void bntAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarProductoActionPerformed
        PanelVistaArticulo pva = new PanelVistaArticulo();
        JLabel aviso = new JLabel("Doble click para seleccionar");
        aviso.setEnabled(false);        
        JOptionPane.showInternalOptionDialog(this, pva, "Seleccione un producto",JOptionPane.OK_CANCEL_OPTION,
                                            JOptionPane.QUESTION_MESSAGE, null, new Object[]{aviso},null);
       if(pva.getAr() != null)
       {
           art = pva.getAr();
           setArticulo();
       }
    }//GEN-LAST:event_bntAgregarProductoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       AdministradorVentanas.mostrarClienteRegistro(this.getDesktopPane(), false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bntNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNuevoActionPerformed
        ExaminadorCampos.habilitarComponentes(pnlBotonesPrincipal, true, true,ExaminadorCampos.TIPO_HABILITAR_POR_NOMBRE);
        ExaminadorCampos.habilitarComponentes(pnlBotonesEdicion, true, true,ExaminadorCampos.TIPO_HABILITAR_POR_NOMBRE);
        ExaminadorCampos.limpiarTexto(pnlEntradas, true,"");
        ExaminadorCampos.limpiarTexto(pnlCantidades, true,"0.0");
        bntRClientes.setEnabled(true);        
        txtNumFactura.setText(Helper.generarCodigo(fc.getUltimoID(), null));       
        cancelado = 0;
        txtPorcentajeDescuento.setText("0");  
        ExaminadorCampos.habilitarComponentes(jPanel3, true, false,ExaminadorCampos.TIPO_HABILITAR_TODO);
        mdva.limpiar();             
        
    }//GEN-LAST:event_bntNuevoActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        ExaminadorCampos.habilitarComponentes(pnlBotonesPrincipal, true, false,ExaminadorCampos.TIPO_HABILITAR_POR_NOMBRE);
        ExaminadorCampos.habilitarComponentes(pnlBotonesEdicion, true, false,ExaminadorCampos.TIPO_HABILITAR_TODO);
        bntSalir.setEnabled(true);
        bntRClientes.setEnabled(false);
        factura = fc.getUltimaFactura();        
        mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
       EventQueue.invokeLater(new Runnable(){

            @Override
            public void run() {
               bntQuitar.setEnabled(false);
               bntModificarCantidad.setEnabled(false);
            }
        })  ;
        tblProductos.setModel(mdva);
        cancelado = 1;
         ExaminadorCampos.habilitarComponentes(jPanel3, true, true,ExaminadorCampos.TIPO_HABILITAR_TODO);
        cargarDatos();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void tblProductosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblProductosFocusLost
        if(cancelado == 0)
        {
            bntModificarCantidad.setEnabled(true); 
            bntQuitar.setEnabled(true);
        }            
    }//GEN-LAST:event_tblProductosFocusLost

    
    public void setCliente(Cliente cl)
    {
        cliente = cl;
        txtCliente.setText(cl.toString());
        txtDireccion.setText(cl.getDireccion());
        txtRuc.setText(cl.getRuc());
        txtTelefono.setText(cl.getTelefono());
    }
    
    public void setArticulo(){
        
        if(art != null)
        {
            if(mdva.existe(art))
            {
                JOptionPane.showInternalMessageDialog(this, "Este producto ya fue agregado.");
                int fl = mdva.getIndice(art);                             
                tblProductos.setRowSelectionInterval(fl, fl);                
                return;
            }
            PanelCantidadArticulo pca = new PanelCantidadArticulo(art);
            JButton[] opciones = pca.getButtons();
            JOptionPane.showInternalOptionDialog(this, pca, "INGRESE LA CANTIDAD QUE DESEA DE ESTE PRODUCTO",JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

            if(pca.getOpcion() == 1)
            {
                if(pca.getFacturaDetalle() == null)
                {
                    System.out.println("Factura detalle nula");
                }
                pca.getFacturaDetalle().setNumeroFactura(txtNumFactura.getText());
                System.out.println(pca.getFacturaDetalle().getArticulo().getDescripcion());
                mdva.agregar(pca.getFacturaDetalle());
                calcularValores();
            }
        }         
       
    }
    
    private void calcularValores()
    {
        subTotal = mdva.getSubtotal();
        descuento = (subTotal*Integer.parseInt(txtPorcentajeDescuento.getText()))/100;
        iva = (subTotal-descuento)*0.12;
        total = subTotal-descuento+iva; 
        this.txtDescuento.setText(String.valueOf(descuento));
        this.txtIva.setText(String.valueOf(iva));
        this.txtSubtotal.setText(String.valueOf(subTotal));
        this.txtTotal.setText(String.valueOf(total));
            
    }
    
    private void cargarDatos()
    {
        if(factura != null)
        {
            this.txtNumFactura.setText(factura.getNumeroFactura());
            txtCliente.setText(factura.getCliente().toString());
            txtDireccion.setText(factura.getCliente().getDireccion());
            txtRuc.setText(factura.getCliente().getRuc());
            txtTelefono.setText(factura.getCliente().getTelefono());            
            cmbVendedor.setSelectedItem(factura.getVendedor());
            this.cmbFormaPago.setSelectedItem(factura.getTipoDePago());
            this.txtPorcentajeDescuento.setText(factura.getDescuento().toString());
            this.txtAreaObservacion.setText(factura.getObservacion());
            this.txtDescuento.setText(factura.getTotalDescuento().toString());
            this.txtIva.setText(factura.getTotalIva().toString());
            this.txtSubtotal.setText(factura.getSubTotal().toString());
            this.txtTotal.setText(String.valueOf((factura.getSubTotal()-factura.getTotalDescuento()+factura.getTotalIva())));
            this.txtPagoInicial.setText(factura.getPagoInicial().toString());
            this.txtSaldo.setText(String.valueOf((factura.getPagoInicial()-(factura.getSubTotal()-factura.getTotalDescuento()+factura.getTotalIva()))));
            this.dcFechaEmision.setDate(factura.getFecha());            
        } 
        
    }
    
    private void cargarEventos()
    {
         ActionListener moodCantidad = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                cambiarCantidadPrd(e);
            }
        };
        bntModificarCantidad.addActionListener(moodCantidad);
        ActionListener quitarProducto = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                eliminarArticulo(e);
            }
        };
        
        bntQuitar.addActionListener(quitarProducto);
        
        ItemListener il = new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent e) {
                vendedor = (Vendedor)e.getItem();
            }
        };
        
        cmbVendedor.addItemListener(il);
        
        ActionListener grabar = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                grabarFactura(e);
            }
        };
        this.bntguardar.addActionListener(grabar);
        
        ActionListener eliminar = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                eliminarFactura();
            }
        };
        
        this.bntEliminar.addActionListener(eliminar);
        
        ActionListener buscar = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarFactura();
            }
        };
        
        this.bntBuscar.addActionListener(buscar);
                
         ActionListener siguie = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                 siguienteRegistro();
            }
        };
         
         this.bntSig.addActionListener(siguie);
         
         ActionListener anterior = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
               registroAnterior();
                
            }
        };
        
        this.bntAnterior.addActionListener(anterior);
        
        ActionListener ultimo = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                 EventQueue.invokeLater(new Runnable(){
                    @Override
                    public void run() {
                       getRegistroFinal();
                    }
                });
                
            }
        };
        
        this.bntUltimo.addActionListener(ultimo);
        
        ActionListener primero = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                 EventQueue.invokeLater(new Runnable(){
                    @Override
                    public void run() {
                       getPrimerRegistro();
                    }
                });
                
            }
        };
        
        this.bntPrimero.addActionListener(primero);
        ListSelectionListener lsl = new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {               
                if(cancelado == 0)
                {
                   ExaminadorCampos.habilitarComponentes(pnlBotonesEdicion, false, true,ExaminadorCampos.TIPO_HABILITAR_POR_NOMBRE); 
                }
            }
        };
        
        
        tblProductos.getSelectionModel().addListSelectionListener(lsl);
        
        ActionListener guardarImprimir = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Integer nu = grabarFactura(e);
                if(nu != null)
                {
                    prepararImpresion();
                }
                
            }
        };
        
        this.bntGuardaImprimir.addActionListener(guardarImprimir);
        
        ActionListener initCalculadora = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                  iniciarCalculadora();            
            }
        };
       this.bntCalculladora.addActionListener(initCalculadora);
       
       ActionListener cerrar = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                  cerrarVentana();            
            }
        };
       
       this.bntSalir.addActionListener(cerrar);
    }
    
    public void cerrarVentana()
    {
        this.dispose();
    }
    public void prepararImpresion()
    {
        PanelImprimible pca = new PanelImprimible(mdva,factura);
            JButton[] opciones = pca.getButtons();
            JOptionPane.showInternalOptionDialog(this, pca, "Imprimir Factura",JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

            if(pca.getOpcion() != null)
            {
                pca.Imprimir();
            }
    }
    
    public void siguienteRegistro()
    {
         
        if(posicionRegistro >= fc.getNumFacturas()) 
        {
            bntSig.setEnabled(false);            
            return;
        }
                
        factura = fc.getPaginadorFactura(posicionRegistro, 1, true);        
        mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
        tblProductos.setModel(mdva);
        this.cargarDatos();
         System.out.println(posicionRegistro);
        bntAnterior.setEnabled(true);
       
        posicionRegistro++;
    }
    
    public void registroAnterior()
    {
        if(posicionRegistro == 0) 
        {
            bntAnterior.setEnabled(false);
            return;
        }
        if(posicionRegistro == fc.getNumFacturas())
        {
            posicionRegistro -=2;
        }else
        {
           posicionRegistro--; 
        }
         
        factura = fc.getPaginadorFactura(posicionRegistro, 1, true);  
        mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
        tblProductos.setModel(mdva);
        this.cargarDatos();
        bntSig.setEnabled(true);
        System.out.println( posicionRegistro);
       
    }
    
    public void getRegistroFinal()
    {
        factura = fc.getUltimaFactura();
        mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
        tblProductos.setModel(mdva);
        this.cargarDatos();
        bntSig.setEnabled(false);
        bntAnterior.setEnabled(true);
        posicionRegistro = fc.getNumFacturas();
    }
    
    public void getPrimerRegistro()
    {
        factura = fc.getPaginadorFactura(0, 1, true);
        mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
        tblProductos.setModel(mdva);
        this.cargarDatos();
        bntAnterior.setEnabled(false);
        bntSig.setEnabled(true);
        posicionRegistro = 1;
    }
    
    
    public void buscarFactura()
    {
        PanelVistaFactura pva = new PanelVistaFactura();
            JLabel lbl = new JLabel("NO HA SELECCIONADO NINGUNA FACTURA");
            lbl.setForeground(Color.red);
            lbl.setVisible(false);
            pva.setAviso(lbl);
            JOptionPane.showInternalOptionDialog(this, pva, "Busquedad de Facturas",JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE, null, new JLabel[]{lbl}, null);
        if(pva.getFactura() != null)    
        {
            factura = pva.getFactura();        
            mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
            tblProductos.setModel(mdva);
            this.cargarDatos();
        }

    }
    public void eliminarFactura()
    {
        String numFac = factura.getNumeroFactura();
        int opcion = JOptionPane.showInternalConfirmDialog(this,"¿Realmente desea eliminar "
                + "la Factura Nro: "+numFac+"?",
                "Factura: "+numFac, JOptionPane.YES_NO_CANCEL_OPTION);
       if(opcion == JOptionPane.OK_OPTION)
       {
            int eliminarRegistro = fc.eliminarRegistro(factura.getNumeroFactura());
            if(eliminarRegistro == 1)
            {
                JOptionPane.showInternalMessageDialog(this, "La Factura Nro. "+numFac+" ha sido eliminada");
                factura = fc.getUltimaFactura();        
                mdva = new ModeloDetalleVentaArticulo(fc,factura.getNumeroFactura());
                tblProductos.setModel(mdva);        
                cargarDatos();
            }
       }
        
    }
    public synchronized Integer grabarFactura(ActionEvent e)
    {
        if(cliente == null)
        {
           mostrarMensaje("Seleccione un cliente"); 
           return null;
        }
         if(vendedor == null)
         {
             mostrarMensaje("Seleccione un Vendedor"); 
             return null;
         }else{
             if(vendedor.getId() == null)
             {
                 mostrarMensaje("Seleccione un Vendedor");
                 return null;
             }
         }
         
         if(mdva.estaVacio())
         {
            mostrarMensaje("Antes de grabar debe agregar por lo menos un articulo");
            return null; 
         }
         
         if(this.cmbFormaPago.getSelectedIndex()!=-1)
         {
             if(this.cmbFormaPago.getSelectedIndex() == 0)
             {
                 mostrarMensaje("Especifique una forma de pago");
                 return null;
             }
         }
         
         if(this.cmbFormaPago.getSelectedIndex()==-1)
         {             
            mostrarMensaje("Especifique una forma de pago");
            cmbFormaPago.requestFocus();
            return null;
         }
         
         factura = new VFactura();
         factura.setNumeroFactura(this.txtNumFactura.getText());
         factura.setCliente(cliente);
         factura.setVendedor(vendedor);
         factura.setTipoDePago(cmbFormaPago.getSelectedItem().toString());
         factura.setFecha(dcFechaEmision.getDate());
         factura.setDescuento(Integer.parseInt(txtPorcentajeDescuento.getText()));
         factura.setTotalDescuento(descuento);
         factura.setSubTotal(subTotal);
         factura.setTotalIva(iva);
         factura.setPagoInicial(total);
         factura.setObservacion(this.txtAreaObservacion.getText());         
         
         int opcion = JOptionPane.showInternalConfirmDialog(this, "¿Realmente desea "
                 + "guardar esta factura?", "Factura Nro: "+txtNumFactura.getText(), JOptionPane.YES_NO_CANCEL_OPTION);
         if(opcion==JOptionPane.OK_OPTION)
         {
             int grabado = fc.grabarRegistro(factura,mdva.getLista());
             if(grabado != 0)
             {
                 JOptionPane.showInternalMessageDialog(this, "Factura Nro: "+txtNumFactura.getText()+
                         "Ha sido procesada correctamente.");
                 return new Integer(1);
             }
         }
         
         return null;
    }
    
    private synchronized void mostrarMensaje(String msg)
    {
        JOptionPane.showInternalMessageDialog(this, msg);
    }
    
    public JFacturas getCnt()
    {
        return this;
    }
    
    public synchronized void cambiarCantidadPrd(ActionEvent ev)
    {
        if(tblProductos.getSelectedRow() != -1)
        {
            
            //JOptionPane.showInternalInputDialog(getCnt(), "Ingrese Nueva Cantidad", "Cambio de Cantidad", JOptionPane.YES_NO_CANCEL_OPTION);
            PanelCantidadArticulo pca = new PanelCantidadArticulo(mdva.getFila(tblProductos.getSelectedRow()));
            JButton[] opciones = pca.getButtons();
            JOptionPane.showInternalOptionDialog(this, pca, "INGRESE LA CANTIDAD QUE DESEA DE ESTE PRODUCTO",JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

            if(pca.getOpcion() == 1)
            {
                if(pca.getFacturaDetalle() == null)
                {
                    System.out.println("Factura detalle nula");
                }               
                System.out.println(pca.getFacturaDetalle().getArticulo().getDescripcion());
                mdva.actualizarFila(tblProductos.getSelectedRow());
                calcularValores();
            }
        }else{
            JOptionPane.showInternalMessageDialog(this, "Primero debe seleccionar un articulo!!");
        }
    }
    
    public synchronized void eliminarArticulo(ActionEvent ev)
    {
        if(tblProductos.getSelectedRow() != -1)
        {
            int opcion = JOptionPane.showConfirmDialog(this, "¿Realmente desea quitar el Articulo:\n"
                    +"Codigo: "+mdva.getFila(tblProductos.getSelectedRow()).getIdArticulo()+"\n"+
                    "Nombre: "+mdva.getFila(tblProductos.getSelectedRow()).getArticulo().getDescripcion()+
                    "?", "Desea quitar el Articulo", JOptionPane.YES_NO_CANCEL_OPTION);
            if(opcion == JOptionPane.OK_OPTION)
            {
                mdva.eliminarFila(tblProductos.getSelectedRow());
                calcularValores();
                if(tblProductos.getRowCount() == 0)
                {
                    this.bntModificarCantidad.setEnabled(false);
                    this.bntQuitar.setEnabled(false);
                }
            }
            
        }else{
            JOptionPane.showInternalMessageDialog(this, "Primerod debe seleccionar un articulo!!");
        }
    }
    
    public void iniciarCalculadora()
    {
        Runtime r=Runtime.getRuntime();
        try
        {
          Process p=r.exec("calc");           
        }catch(Exception e){}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAgregarProducto;
    private javax.swing.JButton bntAnterior;
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton bntCalculladora;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton bntGuardaImprimir;
    private javax.swing.JButton bntModificarCantidad;
    private javax.swing.JButton bntNuevo;
    private javax.swing.JButton bntPrimero;
    private javax.swing.JButton bntQuitar;
    private javax.swing.JButton bntRClientes;
    private javax.swing.JButton bntSalir;
    private javax.swing.JButton bntSig;
    private javax.swing.JButton bntUltimo;
    private javax.swing.JButton bntguardar;
    private javax.swing.JComboBox cmbFormaPago;
    private javax.swing.JComboBox cmbVendedor;
    private com.toedter.calendar.JDateChooser dcFechaEmision;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlBotonesEdicion;
    private javax.swing.JPanel pnlBotonesPrincipal;
    private javax.swing.JPanel pnlCantidades;
    private javax.swing.JPanel pnlEntradas;
    private javax.swing.JPanel pnlEntradas1;
    private javax.swing.JPanel pnlEntradas2;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextArea txtAreaObservacion;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtPagoInicial;
    private javax.swing.JTextField txtPorcentajeDescuento;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
