/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import controller.FacturaController;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelobd.VFactura;
import modelogui.ModeloTablaFactura;
import utilidades.Helper;

/**
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
public class PanelVistaFactura extends javax.swing.JPanel {

    /**
     * Creates new form PanelVistaFactura
     */
    
    private JOptionPane op;
    private ModeloTablaFactura mtf; 
    private VFactura fc;
    private JLabel aviso;
    public PanelVistaFactura() {
        initComponents();
        dcFecha.setVisible(false);
        iniciarCampoFecha();
        mtf = new ModeloTablaFactura();
        tblFacturas.setModel(mtf);
    }

    private void iniciarCampoFecha()
    {
        jPanel1.remove(bntBuscar);
        java.awt.GridBagConstraints gridBagConstraints;       
        dcFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dcFecha.setPreferredSize(new java.awt.Dimension(250, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 8);
        jPanel1.add(dcFecha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 4);
        jPanel1.add(bntBuscar, gridBagConstraints);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        dcFecha = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        rbFactura = new javax.swing.JRadioButton();
        rbFecha = new javax.swing.JRadioButton();
        bntBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();

        dcFecha.setDateFormatString("dd/MM/yyyy");

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar Por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtNumFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumFactura.setPreferredSize(new java.awt.Dimension(250, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 8);
        jPanel1.add(txtNumFactura, gridBagConstraints);

        buttonGroup1.add(rbFactura);
        rbFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFactura.setSelected(true);
        rbFactura.setText("Nro. Factura");
        rbFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFacturaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 5, 0);
        jPanel1.add(rbFactura, gridBagConstraints);

        buttonGroup1.add(rbFecha);
        rbFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFecha.setText("Fecha");
        rbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 5, 0);
        jPanel1.add(rbFecha, gridBagConstraints);

        bntBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntBuscar.setText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 4);
        jPanel1.add(bntBuscar, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(680, 150));

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFacturas);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rbFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFacturaActionPerformed
        txtNumFactura.setVisible(true);
        dcFecha.setVisible(false);
        
    }//GEN-LAST:event_rbFacturaActionPerformed

    private void rbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaActionPerformed
        txtNumFactura.setVisible(false);
        dcFecha.setVisible(true);       
    }//GEN-LAST:event_rbFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aceptar();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       cancelar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        llenarTablaBusqueda();
       
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void tblFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacturasMouseClicked
        if(aviso != null)
        {
            aviso.setVisible(false);
        }
        if(evt.getClickCount() == 2)
        {
            aceptar();
        }
    }//GEN-LAST:event_tblFacturasMouseClicked

    public synchronized void cancelar()
    {
        getOptionPane();
        if(op != null)
        {
            op.setValue(0);
        }
    }
    
    public synchronized void aceptar()
    {
        getOptionPane();
        if(tblFacturas.getSelectedRow() != -1)
        {
            fc = mtf.getFactura(tblFacturas.getSelectedRow());            
            if(op != null)
            {
                op.setValue(1);
            }
        }else{
            if(aviso != null)
            {
                aviso.setVisible(true);
            }
        }
    }
    
    
    public void llenarTablaBusqueda()
    {
        if(rbFactura.isSelected() && !txtNumFactura.getText().isEmpty())
        {
            mtf = new ModeloTablaFactura(FacturaController.POR_CODIGO,txtNumFactura.getText()); 
            tblFacturas.setModel(mtf);
            System.out.println("clickkk clickkk");
        }
        
        if(rbFecha.isSelected() && dcFecha.getCalendar() != null)
        {
            mtf = new ModeloTablaFactura(FacturaController.POR_FECHA,Helper.getFechaFormateada(dcFecha.getDate(),Helper.ANIO_MES_DIA)); 
            tblFacturas.setModel(mtf);
        }
    }
    
     private void getOptionPane()
    {
        if(op != null)
        {
            return;
        }
        Component pdr =this.getParent(); 
        while(pdr.getParent() != null)
        {
            if(pdr instanceof JOptionPane)
            {
                op = (JOptionPane)pdr;
                break;
            }            
            pdr = pdr.getParent();
        }
    }
    
    public VFactura getFactura()
    {
        return fc;
    }
    
    public void setAviso(JLabel aviso)
    {
        this.aviso = aviso;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFactura;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTextField txtNumFactura;
    // End of variables declaration//GEN-END:variables
}
