/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import modelobd.VFactura;
import modelogui.ModeloDetalleVentaArticulo;
import utilidades.Helper;
import utilidades.RedimensionadorDeColumnas;

/**
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
public class PanelImprimible extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form PanelImprimible
     */
    ModeloDetalleVentaArticulo mdva;
    VFactura fc;
    private JOptionPane op;
    private JViewport vp = new JViewport();
    Integer opcion;
    public PanelImprimible() {
        initComponents();
    }

    public PanelImprimible(ModeloDetalleVentaArticulo mdva, VFactura fc) {
        this.mdva = mdva;
        this.fc = fc;
        vp.setBackground(Color.WHITE);
        initComponents();
        this.lbFecha.setText(Helper.getFechaFormateada(fc.getFecha(), Helper.DIA_MES_ANIO));
        this.lbNumero.setText(fc.getNumeroFactura());
        this.lbCliente.setText(fc.getCliente().toString());
        this.lbVendedor.setText(fc.getVendedor().toString());
        tblDetalle.setModel(mdva); 
        //tblDetalle.getColumnModel().getColumn(1).setWidth(350);
        RedimensionadorDeColumnas.ajustarAnchoColumnas(tblDetalle);
    }
    
     private void getOptionPane()
    {
        if(op != null)
        {
            return;
        }
        Component pdr =this.getParent(); 
        while(pdr.getParent() != null)
        {
            if(pdr instanceof JOptionPane)
            {
                op = (JOptionPane)pdr;
                break;
            }            
            pdr = pdr.getParent();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bntImprimir = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbVendedor = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();

        bntImprimir.setText("Imprimir");
        bntImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntImprimirActionPerformed(evt);
            }
        });

        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setPreferredSize(new java.awt.Dimension(650, 300));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 82, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(jLabel2, gridBagConstraints);

        lbCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCliente.setText("jLabel3");
        lbCliente.setPreferredSize(new java.awt.Dimension(260, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lbCliente, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Vendedor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 3);
        jPanel1.add(jLabel4, gridBagConstraints);

        lbVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbVendedor.setText("jLabel5");
        lbVendedor.setPreferredSize(new java.awt.Dimension(260, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        jPanel1.add(lbVendedor, gridBagConstraints);

        lbFecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbFecha.setPreferredSize(new java.awt.Dimension(100, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lbFecha, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 82, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        lbNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNumero.setText("jLabel7");
        lbNumero.setPreferredSize(new java.awt.Dimension(100, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(lbNumero, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewport(vp);

        tblDetalle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalle.setEnabled(false);
        tblDetalle.setGridColor(new java.awt.Color(153, 204, 255));
        tblDetalle.setPreferredSize(new java.awt.Dimension(450, 64));
        tblDetalle.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblDetalle);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bntImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntImprimirActionPerformed
        getOptionPane();
        opcion = 1;
        op.setValue(1);
        
    }//GEN-LAST:event_bntImprimirActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
       getOptionPane();
       op.setValue(0);
    }//GEN-LAST:event_bntCancelarActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JTable tblDetalle;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        try
    {
    if (pageIndex > 0)
    { 
      return NO_SUCH_PAGE;
    }
      Graphics2D g2d = (Graphics2D)graphics;
      g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
      this.printAll(graphics);
      return PAGE_EXISTS;
    }
    catch(Exception ex)
        {
            JOptionPane.showMessageDialog( null, "NO HAY OBJETOS A IMPRIMIR", "ERROR DE IMPRESION", JOptionPane.ERROR_MESSAGE);
        }
    return PAGE_EXISTS;
    }    
    
    public JButton[] getButtons()
    {
        return new JButton[]{bntImprimir,bntCancelar};
    }
    
    public void Imprimir()
    {
        try{
                try
                {
                  PrinterJob job = PrinterJob.getPrinterJob();
                  job.setPrintable(this);
                  job.printDialog();
                  job.print();
                }
                catch (PrinterException ex)
                {
                    
                }
             }catch(Exception ex)
        {
            
        }
    }

    public Integer getOpcion() {
        return opcion;
    }
    
    
        
  
}
